import { SERIES_QUESTION_BANKS, SERIES_FINDINGS } from './seriesQuestionBanks';
import { worked, practice, scene, makeSection } from './lowerSixLessonKit';

// Form 5 Series and Sequences: original explanations and worked examples.
// Scope is described in SOURCES.md. Practice questions are generated and checked by
// scripts/generateLower6SeriesPractice.py.
const section = makeSection(SERIES_QUESTION_BANKS, SERIES_FINDINGS);

export const SERIES_SECTIONS = [
  section('sequences', 'Sequences & Notation', 'A sequence is a list of numbers in a set order. Each number is called a term. We start with the language and the notation.', [
    { p: 'The list 2, 5, 8, 11, … is a **sequence**. The first term is written `u₁`, the second `u₂`, and the **nth term** is `uₙ`. The small number is called the **subscript**: it tells you the position of the term in the list. A **series** is what you get when you add the terms of a sequence together.' },
    { diagram: 'sequence', caption: 'The graph of uₙ = 3n − 2 is a set of separate points. A sequence is only defined for n = 1, 2, 3, … so there is nothing between the dots.' },
    { h: 'Two ways to describe a sequence' },
    { p: 'A **formula** gives uₙ directly from n. For example, `uₙ = 3n − 2` gives u₁ = 1, u₂ = 4, u₃ = 7, … and you can find u₁₀₀ without finding the earlier terms.' },
    { p: 'A **recurrence relation** (or inductive definition) gives each term from the one before. For example, `u₁ = 2` and `uₙ₊₁ = 3uₙ − 1`. You must be told the first term. To find u₁₀₀ you would need all the terms before it.' },
    worked('Terms from a formula', 'A sequence has uₙ = n² + 1. Find u₁, u₂, u₃ and the value of n for which uₙ = 50.', '2, 5, 10; n = 7', [
      ['u₁ = 1² + 1 = 2', 'Put n = 1 in the formula.'],
      ['u₂ = 2² + 1 = 5 and u₃ = 3² + 1 = 10', 'Put n = 2, then n = 3.'],
      ['n² + 1 = 50, so n² = 49', 'To find which term equals 50, put uₙ = 50 and solve for n.'],
      ['n = 7', 'We need a positive whole number, so we reject n = −7.'],
    ]),
    worked('Terms from a recurrence', 'A sequence has u₁ = 4 and uₙ₊₁ = 2uₙ − 3. Find u₂, u₃ and u₄.', '5, 7, 11', [
      ['u₂ = 2(4) − 3 = 5', 'Put the last term in place of uₙ.', scene('u₁ = 4; uₙ₊₁ = 2uₙ − 3', 'u₂ = 2(4) − 3', ['4', '2', '3'], 'The recurrence says: double the last term, then take away 3.')],
      ['u₃ = 2(5) − 3 = 7', 'Use u₂ = 5 as the last term.'],
      ['u₄ = 2(7) − 3 = 11', 'Use u₃ = 7 as the last term.'],
    ]),
    { h: 'Sigma notation' },
    { p: 'The Greek capital letter **Σ** (sigma) means "add up". `Σ(r = 1 to 4) (2r + 1)` means put r = 1, 2, 3, 4 into 2r + 1 and add the results: 3 + 5 + 7 + 9 = 24. The number under the sigma is where r starts. The number above is where it stops. The letter r is only a counter, so any letter will do.' },
    { h: 'Kinds of sequence' },
    { table: [['Type', 'What happens', 'Example'], ['Increasing', 'uₙ₊₁ > uₙ for every n', '2, 5, 8, 11, …'], ['Decreasing', 'uₙ₊₁ < uₙ for every n', '1, 1/2, 1/3, 1/4, …'], ['Periodic', 'The terms repeat in a cycle', '2, −1, 1/2, 2, −1, 1/2, …'], ['Convergent', 'The terms get closer to a limit', '1, 1/2, 1/4, 1/8, … (limit 0)']] },
    { p: 'To show a sequence is **increasing**, work out `uₙ₊₁ − uₙ` and show that it is positive for every n.' },
    practice(['Find the first four terms of `uₙ = 2ⁿ`.', 'A sequence has `u₁ = 1` and `uₙ₊₁ = uₙ + 2n`. Find u₂, u₃, u₄.'], ['2, 4, 8, 16', '2, 6, 12']),
  ]),
  section('ap', 'Arithmetic Progressions', 'An arithmetic progression (AP) goes up or down by the same amount each time.', [
    { p: 'In an **arithmetic progression**, every term is found by adding the same number to the one before. This number is the **common difference**, d. For 3, 7, 11, 15, … the first term is a = 3 and the common difference is d = 4. If d is negative, the terms go down.' },
    { diagram: 'ap', caption: 'The terms 2, 5, 8, 11, … go up by 3 each time, so the points lie on a straight line. The common difference is the gradient of that line.' },
    { f: 'uₙ = a + (n − 1)d' },
    { p: 'Why n − 1? To reach the 5th term you start at a and add d four times, not five. The first term needs no steps.' },
    worked('Finding a term', 'Find the 12th term of the AP 7, 11, 15, … and the position of the term 99.', 'u₁₂ = 51; 99 is the 24th term', [
      ['a = 7 and d = 4', 'Read off the first term and the common difference.'],
      ['u₁₂ = 7 + 11(4) = 51', 'Put n = 12 in uₙ = a + (n − 1)d.', scene('a = 7; d = 4; n = 12', 'u₁₂ = 7 + 11(4)', [['7', '7'], ['4', '4']], 'The bracket (n − 1) is 11, because n is 12.')],
      ['7 + (n − 1)4 = 99', 'To find the position of 99, put uₙ = 99.'],
      ['(n − 1)4 = 92, so n − 1 = 23 and n = 24', 'n must be a positive whole number. It is.'],
    ]),
    { h: 'The sum of an AP' },
    { p: 'To add 1 + 2 + 3 + … + 100, write the sum forwards and backwards. Each pair adds to 101, and there are 100 pairs, which counts every term twice. So the sum is 100 × 101/2 = 5050. The same idea works for any AP.' },
    { f: 'Sₙ = n/2 [2a + (n − 1)d] = n/2 (a + l)' },
    { p: 'Here l is the **last term**. Use the second form when you know the first and last terms. Use the first form when you know a, d and n.' },
    worked('Sum of an AP', 'Find the sum of the first 12 terms of the AP 7, 11, 15, …', 'S₁₂ = 348', [
      ['S₁₂ = 12/2 [2(7) + 11(4)]', 'Put a = 7, d = 4 and n = 12 into the sum formula.', scene('a = 7; d = 4; n = 12', 'S₁₂ = 12/2 [2(7) + 11(4)]', [['12', '12'], ['7', '7'], ['4', '4']], 'n is the number of terms. a and d go inside the brackets.')],
      ['S₁₂ = 6 × 58', 'Work out the bracket: 14 + 44 = 58.'],
      ['S₁₂ = 348', 'Multiply.'],
    ]),
    worked('A real situation', 'A theatre has 20 seats in the first row. Each row has 2 more seats than the one in front. How many seats are there in 15 rows?', '510 seats', [
      ['This is an AP with a = 20 and d = 2', 'Each row adds the same number of seats.'],
      ['S₁₅ = 15/2 [2(20) + 14(2)]', 'We want the total, so use the sum formula with n = 15.'],
      ['S₁₅ = 15/2 × 68 = 510', 'Work out the bracket: 40 + 28 = 68. Then 15 × 34 = 510.'],
    ]),
    { p: '**Common mistake:** the sum formula needs the number of terms, n. If you are given the first and last terms, find n first using `l = a + (n − 1)d`. When a question gives two facts about an AP, write an equation for each and solve them together.' },
    practice(['Find the 30th term of 2, 5, 8, …', 'Find the sum of the first 20 terms of 3, 7, 11, …'], ['89', '820']),
  ]),
  section('gp', 'Geometric Progressions', 'A geometric progression (GP) multiplies by the same number each time.', [
    { p: 'In a **geometric progression**, every term is found by multiplying the one before by the same number. This number is the **common ratio**, r. For 3, 6, 12, 24, … the first term is a = 3 and r = 2. To find r, divide any term by the one before it. If r is negative the signs alternate. If r is between 0 and 1 the terms shrink.' },
    { diagram: 'gp', caption: 'Each bar is twice as tall as the last. A GP with r > 1 grows faster and faster, unlike an AP, which grows by the same amount each time.' },
    { f: 'uₙ = ar^(n − 1)' },
    { table: [['', 'AP', 'GP'], ['Rule', 'Add d each time', 'Multiply by r each time'], ['nth term', 'a + (n − 1)d', 'ar^(n − 1)'], ['Test', 'Differences are equal', 'Ratios are equal'], ['Graph of uₙ', 'Points on a straight line', 'Points on a curve']] },
    worked('Finding a term', 'A GP has a = 4 and r = 3. Find the 6th term.', 'u₆ = 972', [
      ['u₆ = 4 × 3⁵', 'Use uₙ = ar^(n − 1) with n = 6. The power is n − 1 = 5.', scene('a = 4; r = 3; n = 6', 'u₆ = 4 × 3^5', [['4', '4'], ['3', '3']], 'The ratio is raised to the power n − 1, not n.')],
      ['u₆ = 4 × 243 = 972', '3⁵ = 3 × 3 × 3 × 3 × 3 = 243.'],
    ]),
    { h: 'The sum of a GP' },
    { p: 'Write `Sₙ = a + ar + ar² + … + ar^(n − 1)`. Multiply by r: `rSₙ = ar + ar² + … + arⁿ`. Subtract. Nearly every term cancels, leaving `Sₙ − rSₙ = a − arⁿ`. So `Sₙ(1 − r) = a(1 − rⁿ)`.' },
    { f: 'Sₙ = a(1 − rⁿ)/(1 − r)  =  a(rⁿ − 1)/(r − 1)' },
    { p: 'Use whichever form has the positive bottom line: the first when r < 1, the second when r > 1. They give the same answer. If r = 1, every term is a, and Sₙ = na.' },
    worked('Sum of a GP', 'Find the sum of the first 6 terms of the GP 4, 12, 36, …', 'S₆ = 1456', [
      ['a = 4 and r = 3', 'r = 12/4 = 3.'],
      ['S₆ = 4(3⁶ − 1)/(3 − 1)', 'r > 1, so use the second form.'],
      ['S₆ = 4(728)/2 = 1456', '3⁶ = 729, so 3⁶ − 1 = 728.'],
    ]),
    worked('Growth', 'A town has 2000 people. Its population grows by 8% each year. Find its population after 5 years.', 'About 2939 people', [
      ['Each year the population is multiplied by 1.08', '8% more means 108% of the old value.'],
      ['After 5 years: 2000 × 1.08⁵', 'This is the 6th term of a GP with a = 2000 and r = 1.08. Starting value is the term for year 0.'],
      ['2000 × 1.469328 = 2938.66', 'Use a calculator for 1.08⁵.'],
      ['About 2939 people', 'People are whole numbers, so round.'],
    ]),
    { p: '**Finding n:** when the unknown is a power, take logs. For example, `2ⁿ > 1000` becomes `n ln 2 > ln 1000`, so `n > 9.97`, and the least whole n is 10. Do not divide by a negative log without turning the inequality around.' },
    practice(['Find the 7th term of 5, 10, 20, …', 'Find the sum of the first 5 terms of 81, 27, 9, …'], ['320', '121']),
  ]),
  section('suminf', 'Sum to Infinity', 'Some GPs can be added for ever and still give a finite total.', [
    { p: 'Take 8 + 4 + 2 + 1 + 1/2 + … The partial sums are 8, 12, 14, 15, 15.5, … They keep getting closer to 16 but never pass it. We say the series **converges** to 16, and 16 is its **sum to infinity**.' },
    { diagram: 'convergence', caption: 'The partial sums S₁, S₂, S₃, … climb towards the dashed line at 16. That value is the sum to infinity.' },
    { p: 'This happens when the common ratio satisfies **|r| < 1**, that is −1 < r < 1. Then rⁿ gets closer and closer to 0 as n grows. In the sum formula, `Sₙ = a(1 − rⁿ)/(1 − r)`, the rⁿ part disappears.' },
    { f: 'S∞ = a/(1 − r),  for |r| < 1' },
    { p: 'If |r| ≥ 1 the terms do not shrink, so the sum does not settle on a number: the series **diverges** and there is no sum to infinity.' },
    worked('Sum to infinity', 'Find the sum to infinity of 12 + 3 + 3/4 + …', 'S∞ = 16', [
      ['a = 12 and r = 3/12 = 1/4', 'Divide the second term by the first.'],
      ['|r| = 1/4 < 1, so the series converges', 'Always check this first.'],
      ['S∞ = 12/(1 − 1/4)', 'Put a and r into a/(1 − r).', scene('a = 12; r = 1/4', 'S∞ = 12/(1 − 1/4)', [['12', '12'], ['1/4', '1/4']], 'a goes on top. 1 minus r goes below.')],
      ['S∞ = 12/(3/4) = 12 × 4/3 = 16', 'Dividing by 3/4 is the same as multiplying by 4/3.'],
    ]),
    { h: 'Recurring decimals' },
    { p: 'A recurring decimal is a GP in disguise. 0.7777… = 0.7 + 0.07 + 0.007 + … has a = 0.7 and r = 0.1.' },
    worked('Recurring decimal', 'Write 0.7777… as a fraction.', '7/9', [
      ['0.7 + 0.07 + 0.007 + … is a GP', 'Each term is a tenth of the one before.'],
      ['a = 0.7 and r = 0.1', 'The first term is 0.7.'],
      ['S∞ = 0.7/(1 − 0.1) = 0.7/0.9 = 7/9', 'Multiply top and bottom by 10 to clear the decimals.'],
    ]),
    { h: 'Convergence for a range of x' },
    worked('Values of x', 'For what values of x does 1 + x/3 + x²/9 + … converge? Find its sum.', '−3 < x < 3; S∞ = 3/(3 − x)', [
      ['a = 1 and r = x/3', 'Divide the second term by the first.'],
      ['|x/3| < 1', 'The condition for a sum to infinity.'],
      ['−3 < x < 3', 'Multiply all three parts by 3.'],
      ['S∞ = 1/(1 − x/3) = 3/(3 − x)', 'Multiply top and bottom by 3.'],
    ]),
    { p: '**Common mistake:** you cannot use S∞ = a/(1 − r) when |r| ≥ 1. Also, S∞ is not a term of the sequence: it is the limit of the partial sums. The difference `S∞ − Sₙ = arⁿ/(1 − r)` tells you how far Sₙ is from the limit.' },
    practice(['Find S∞ for 20 + 4 + 0.8 + …', 'Write 0.1212… as a fraction.'], ['25', '4/33']),
  ]),
  section('sigma', 'Sigma Notation & Standard Sums', 'Sigma notation is a short way to write a sum. Three standard results let us add many terms at once.', [
    { p: '`Σ(r = 1 to n) f(r)` means: put r = 1, 2, 3, …, n into f(r) and add. Two rules save work: the sum of a sum is the sum of the sums, and a constant factor comes outside. In symbols, `Σ(af(r) + bg(r)) = aΣf(r) + bΣg(r)`. Adding the constant c a total of n times gives `nc`.' },
    { diagram: 'sigma', caption: 'Two copies of 1 + 2 + 3 + 4 + 5 fit together into a 5 by 6 rectangle of dots. That is why Σr = 5 × 6/2 = 15.' },
    { table: [['Sum', 'Formula'], ['Σ(r = 1 to n) 1', 'n'], ['Σ r', 'n(n + 1)/2'], ['Σ r²', 'n(n + 1)(2n + 1)/6'], ['Σ r³', 'n²(n + 1)²/4,  which is [n(n + 1)/2]²']] },
    { p: 'Notice that Σr³ is the square of Σr. You will need to learn these three results. In exams they are usually given on the formula sheet, but you must still know how to use them.' },
    worked('Find a formula', 'Show that Σ(r = 1 to n) (2r + 3) = n(n + 4).', 'n(n + 4)', [
      ['2Σr + Σ3', 'Take the 2 outside, and split the sum.'],
      ['2 × n(n + 1)/2 + 3n', 'Σr = n(n + 1)/2, and adding 3 a total of n times gives 3n.'],
      ['n(n + 1) + 3n = n² + n + 3n', 'The 2 and the 1/2 cancel.'],
      ['n² + 4n = n(n + 4)', 'Factorise. Check n = 1: the sum is 5, and 1 × 5 = 5.'],
    ]),
    worked('Evaluate a sum', 'Evaluate Σ(r = 1 to 10) (r² − 3r).', '220', [
      ['Σr² − 3Σr', 'Split, and take the 3 outside.'],
      ['10 × 11 × 21/6 − 3 × 10 × 11/2', 'Put n = 10 in each standard result.'],
      ['385 − 165 = 220', '10 × 11 × 21/6 = 385 and 3 × 55 = 165.'],
    ]),
    { h: 'A sum that does not start at 1' },
    { p: 'The standard results start at r = 1. To add from r = a to r = b, take the sum to b, and subtract the sum to a − 1.' },
    worked('Starting later', 'Evaluate Σ(r = 11 to 20) r².', '2485', [
      ['Σ(1 to 20) r² − Σ(1 to 10) r²', 'The terms from 11 to 20 are what is left after removing the first 10.'],
      ['20 × 21 × 41/6 − 10 × 11 × 21/6', 'Put n = 20, then n = 10, in n(n + 1)(2n + 1)/6.'],
      ['2870 − 385 = 2485', 'Work out each part and subtract.'],
    ]),
    { p: '**Tip:** after finding a formula for the sum, test it with n = 1 and n = 2. The sum to n = 1 is just the first term. Factorise as far as you can, so the answer is easy to check.' },
    practice(['Find `Σ(r = 1 to 8) r³`.', 'Show `Σ(r = 1 to n) (4r − 1) = n(2n + 1)`.'], ['1296', '4n(n + 1)/2 − n = 2n² + n']),
  ]),
  section('differences', 'Method of Differences', 'Some sums collapse because almost every term cancels. This is the method of differences.', [
    { p: 'Suppose each term can be written as a difference, `f(r) − f(r + 1)`. Add the terms for r = 1, 2, …, n and look at what happens: the second part of each term cancels the first part of the next. Only the very first and very last parts survive. This is also called a **telescoping** sum, because it folds up like a telescope.' },
    { diagram: 'telescope', caption: 'In Σ 1/[r(r + 1)], each bracket ends with a fraction that the next bracket begins with. Everything cancels except the 1 at the start and the last fraction at the end.' },
    { h: 'The method' },
    { p: '1. Use partial fractions to split the term into a difference. 2. Write out the first three or four terms and the last two. 3. Cross out the pairs that cancel. 4. Collect what is left and simplify. If the question asks for the sum to infinity, let n get very large: fractions like 1/(n + 1) go to 0.' },
    worked('A first example', 'Show that Σ(r = 1 to n) 1/[r(r + 1)] = n/(n + 1). Then find the sum to infinity.', 'n/(n + 1); S∞ = 1', [
      ['1/[r(r + 1)] = 1/r − 1/(r + 1)', 'Partial fractions: put A/r + B/(r + 1) and find A = 1 and B = −1.'],
      ['(1 − 1/2) + (1/2 − 1/3) + … + (1/n − 1/(n + 1))', 'Write out the sum, from r = 1 to the last term r = n.'],
      ['1 − 1/(n + 1)', 'Every middle part cancels, leaving the first 1 and the last −1/(n + 1).'],
      ['= n/(n + 1)', 'Put over a common bottom line.'],
      ['As n → ∞, 1/(n + 1) → 0, so S∞ = 1', 'The partial sums get closer and closer to 1.'],
    ]),
    worked('Terms two apart', 'Find Σ(r = 1 to n) 1/[r(r + 2)]. Then find the sum to infinity.', '3/4 − (2n + 3)/[2(n + 1)(n + 2)]; S∞ = 3/4', [
      ['1/[r(r + 2)] = ½[1/r − 1/(r + 2)]', 'Partial fractions give A = ½ and B = −½.'],
      ['½[(1 − 1/3) + (1/2 − 1/4) + (1/3 − 1/5) + …]', 'Write out several terms. The cancelling now happens two steps apart.'],
      ['Left: 1 and 1/2 at the start, −1/(n + 1) and −1/(n + 2) at the end', 'Everything between cancels.'],
      ['Sₙ = ½[3/2 − 1/(n + 1) − 1/(n + 2)]', 'Collect what is left.'],
      ['S∞ = ½ × 3/2 = 3/4', 'The last two fractions go to 0 as n gets large.'],
    ]),
    { p: '**Common mistake:** when terms are two steps apart, four parts survive, not two. Always write out enough terms to see the pattern: at least the first three and the last two. A sum such as Σ[(r + 1)² − r²] needs no partial fractions: it is already a difference, and it collapses to (n + 1)² − 1.' },
    practice(['Find `Σ(r = 1 to n) [(r + 1)³ − r³]`.', 'Find the sum to infinity of `Σ 1/[(r + 1)(r + 2)]` from r = 1.'], ['(n + 1)³ − 1', '1/2']),
  ]),
  section('binomint', 'Binomial Expansion (Positive Integer n)', 'A binomial has two terms, such as a + b. We learn a quick way to expand (a + b)ⁿ.', [
    { p: 'Expanding `(a + b)²` gives a² + 2ab + b². Expanding `(a + b)³` gives a³ + 3a²b + 3ab² + b³. The numbers in front of each term, 1, 2, 1 and 1, 3, 3, 1, are the **binomial coefficients**. They come from **Pascal\'s triangle**: each number is the sum of the two above it.' },
    { diagram: 'pascal', caption: 'Row n of Pascal\'s triangle gives the coefficients for (a + b)ⁿ. For example, row 4 is 1, 4, 6, 4, 1.' },
    { p: 'For large n, use the formula `ⁿCᵣ = n!/[r!(n − r)!]`, where `n! = n × (n − 1) × … × 2 × 1`. For example, `⁸C₃ = 8 × 7 × 6/(3 × 2 × 1) = 56`. The coefficients are symmetrical: `ⁿCᵣ = ⁿCₙ₋ᵣ`.' },
    { f: '(a + b)ⁿ = aⁿ + ⁿC₁ aⁿ⁻¹b + ⁿC₂ aⁿ⁻²b² + … + bⁿ' },
    { p: 'The power of a goes down by one each term, and the power of b goes up by one. The **general term** is `ⁿCᵣ aⁿ⁻ʳ bʳ`. There are n + 1 terms in total.' },
    worked('Expand a bracket', 'Expand (1 + 2x)⁴ in ascending powers of x.', '1 + 8x + 24x² + 32x³ + 16x⁴', [
      ['Coefficients from row 4: 1, 4, 6, 4, 1', 'Use Pascal\'s triangle, or ⁴Cᵣ.'],
      ['(1)⁴ + 4(1)³(2x) + 6(1)²(2x)² + 4(1)(2x)³ + (2x)⁴', 'Put a = 1 and b = 2x. Keep the whole of 2x inside the bracket when you raise it to a power.'],
      ['1 + 8x + 6(4x²) + 4(8x³) + 16x⁴', '(2x)² = 4x², (2x)³ = 8x³ and (2x)⁴ = 16x⁴.'],
      ['1 + 8x + 24x² + 32x³ + 16x⁴', 'Multiply out the numbers.'],
    ]),
    worked('One coefficient', 'Find the coefficient of x³ in the expansion of (3 − x)⁵.', '−90', [
      ['The x³ term has r = 3: ⁵C₃ (3)² (−x)³', 'The power of b = −x is the power of x we want.'],
      ['10 × 9 × (−x³)', '⁵C₃ = 10, 3² = 9, and (−x)³ = −x³.'],
      ['−90x³, so the coefficient is −90', 'Keep the minus sign.'],
    ]),
    worked('Term independent of x', 'Find the term independent of x in (x² + 1/x)⁶.', '15', [
      ['General term: ⁶Cᵣ (x²)⁶⁻ʳ (1/x)ʳ = ⁶Cᵣ x^(12 − 3r)', '(x²)⁶⁻ʳ = x^(12 − 2r) and (1/x)ʳ = x^(−r), so the powers add to 12 − 3r.'],
      ['12 − 3r = 0, so r = 4', '"Independent of x" means the power of x is 0.'],
      ['⁶C₄ = 15', 'There are no other factors, so the term is 15.'],
    ]),
    worked('An approximation', 'Use the first three terms of (1 − x)⁵ to estimate 0.98⁵.', '0.904', [
      ['(1 − x)⁵ = 1 − 5x + 10x² − …', 'Expand with b = −x.'],
      ['Put x = 0.02', '0.98 = 1 − 0.02.'],
      ['1 − 0.1 + 10(0.0004) = 1 − 0.1 + 0.004 = 0.904', 'The calculator gives 0.90392, so the estimate is very close. The later terms are very small.'],
    ]),
    practice(['Expand `(1 + x)^5`.', 'Find the coefficient of x² in `(2 − 3x)^4`.'], ['1 + 5x + 10x² + 10x³ + 5x⁴ + x⁵', '216']),
  ]),
  section('binomrat', 'The Binomial Series (Any n)', 'The binomial series also works when n is negative or a fraction. Then it goes on for ever.', [
    { p: 'When n is a positive whole number, the expansion stops after n + 1 terms. When n is negative or a fraction, it never stops: the result is an **infinite series**. The formula starts with a 1, so write your bracket as `(1 + u)ⁿ`.' },
    { f: '(1 + u)ⁿ = 1 + nu + n(n − 1)u²/2! + n(n − 1)(n − 2)u³/3! + …' },
    { p: 'This is valid only when **|u| < 1**. If |u| ≥ 1 the terms do not get smaller and the series is no use. If u = 2x, the condition is |2x| < 1, so |x| < 1/2.' },
    { diagram: 'binomapprox', caption: 'Adding more terms of (1 + x)^(1/2) makes the polynomial fit √(1 + x) better. Outside −1 < x < 1 the fit fails.' },
    worked('A first expansion', 'Expand (1 − 4x)^(1/2) up to the term in x³. State when it is valid.', '1 − 2x − 2x² − 4x³; |x| < 1/4', [
      ['n = 1/2 and u = −4x', 'Compare with (1 + u)ⁿ.'],
      ['n(n − 1)/2! = (1/2)(−1/2)/2 = −1/8; n(n − 1)(n − 2)/3! = 1/16', 'Work out the two coefficients.'],
      ['1 + (1/2)(−4x) − (1/8)(−4x)² + (1/16)(−4x)³', 'Put u = −4x everywhere. Keep brackets round −4x.'],
      ['1 − 2x − (1/8)(16x²) + (1/16)(−64x³)', '(−4x)² = 16x² and (−4x)³ = −64x³.'],
      ['1 − 2x − 2x² − 4x³', 'Simplify.'],
      ['|−4x| < 1, so |x| < 1/4', 'Valid for −1/4 < x < 1/4.'],
    ]),
    { h: 'Take out a factor first' },
    { p: 'If the bracket does not start with 1, take out the first term. For example, `(9 + x)^(1/2) = [9(1 + x/9)]^(1/2) = 3(1 + x/9)^(1/2)`. Remember to take the power of the constant: 9^(1/2) = 3. The condition is now |x/9| < 1, that is |x| < 9.' },
    worked('A factor outside', 'Expand √(9 + x) up to the term in x³.', '3 + x/6 − x²/216 + x³/3888', [
      ['√(9 + x) = 3(1 + x/9)^(1/2)', 'Take out 9, which gives 9^(1/2) = 3.'],
      ['(1 + u)^(1/2) = 1 + u/2 − u²/8 + u³/16 − …', 'Use n = 1/2, with u = x/9.'],
      ['1 + x/18 − x²/648 + x³/11664', 'Put u = x/9: u/2 = x/18, u²/8 = x²/648, and u³/16 = x³/11664.'],
      ['3 + x/6 − x²/216 + x³/3888', 'Multiply every term by 3.'],
    ]),
    worked('An approximation', 'Use the first three terms of (1 + x)^(1/3) to estimate ∛1.03.', '1.0099', [
      ['(1 + x)^(1/3) = 1 + x/3 − x²/9 + …', 'n = 1/3: n(n − 1)/2 = (1/3)(−2/3)/2 = −1/9.'],
      ['Put x = 0.03: 1 + 0.01 − 0.0009/9', '0.03/3 = 0.01 and 0.03² = 0.0009.'],
      ['1 + 0.01 − 0.0001 = 1.0099', 'Check with a calculator: ∛1.03 = 1.00990.'],
    ]),
    { p: '**Partial fractions:** split an expression such as `1/[(1 − x)(1 + 2x)]` into `A/(1 − x) + B/(1 + 2x)`, then expand each part. The combined series is only valid where both parts are valid, so choose the smaller range. Here that is |x| < 1/2.' },
    practice(['Expand `(1 + x)^(−1/2)` up to x³.', 'State when `(1 − 2x)^(1/2)` is valid.'], ['1 − x/2 + 3x²/8 − 5x³/16', '|x| < 1/2']),
  ]),
  section('recurrence', 'Recurrence Relations & Convergence', 'A recurrence relation builds a sequence one term at a time. Some settle down to a limit.', [
    { p: 'A recurrence has the form `uₙ₊₁ = f(uₙ)`: to get the next term, apply the same rule to the last term. Starting from u₁, you can find as many terms as you like. A calculator\'s **Ans** button does this quickly.' },
    { p: 'If the terms get closer and closer to a number L, the sequence **converges** to the **limit** L. Far along the sequence, uₙ and uₙ₊₁ are both almost L, so L must satisfy `L = f(L)`. Solving this equation gives the limit.' },
    worked('Find the limit', 'A sequence has u₁ = 1 and uₙ₊₁ = (uₙ + 8)/3. Find u₂, u₃ and the limit.', 'u₂ = 3, u₃ = 11/3; L = 4', [
      ['u₂ = (1 + 8)/3 = 3', 'Put u₁ = 1 in the rule.'],
      ['u₃ = (3 + 8)/3 = 11/3', 'Put u₂ = 3 in the rule.'],
      ['L = (L + 8)/3', 'If the sequence converges, L stands for both uₙ and uₙ₊₁.'],
      ['3L = L + 8, so 2L = 8 and L = 4', 'Solve. The terms 1, 3, 3.67, 3.89, … do head towards 4.'],
    ]),
    { table: [['Rule', 'Converges?', 'Limit'], ['uₙ₊₁ = kuₙ + c, with |k| < 1', 'Yes, from any start', 'c/(1 − k)'], ['uₙ₊₁ = kuₙ + c, with |k| > 1', 'No, unless it starts exactly at the limit', '—'], ['uₙ₊₁ = √(2uₙ + 3)', 'Yes, from u₁ = 1', 'L² = 2L + 3 gives L = 3 (reject −1)']] },
    { p: 'When solving for L, you may get more than one answer. Check which one makes sense: for example, a square root cannot give a negative number.' },
    { h: 'Iteration to find a root' },
    { p: 'An equation such as `x³ − x − 1 = 0` is hard to solve exactly. Rearrange it into the form `x = g(x)`. Then use `xₙ₊₁ = g(xₙ)`. Each answer feeds the next. If the values settle, they settle on a root. First show that a root exists: if f changes sign between two numbers, f(x) = 0 somewhere between them.' },
    { diagram: 'cobweb', caption: 'Starting at x₀ = 1, each step goes up to the curve and across to the line y = x. The steps spiral in towards the root where they meet.' },
    worked('Fixed-point iteration', 'Show that x³ − x − 1 = 0 has a root between 1 and 2. Use xₙ₊₁ = (xₙ + 1)^(1/3) with x₀ = 1 to find x₁ to x₄.', 'x₁ = 1.2599, x₂ = 1.3123, x₃ = 1.3224, x₄ = 1.3243', [
      ['f(1) = −1 and f(2) = 5', 'Let f(x) = x³ − x − 1. The sign changes from negative to positive.'],
      ['So there is a root between 1 and 2', 'f is continuous, so it must cross zero.'],
      ['x³ = x + 1, so x = (x + 1)^(1/3)', 'Rearrange the equation to the form x = g(x).'],
      ['x₁ = (1 + 1)^(1/3) = 1.2599', 'Put x₀ = 1. Use the Ans button for the next steps.'],
      ['x₂ = 1.3123, x₃ = 1.3224, x₄ = 1.3243', 'Each answer is put back in. The values settle near 1.3247.'],
    ]),
    { p: '**Check:** the iteration only works if the steps spiral inwards. For a correct rearrangement, the gradient of g near the root must have size less than 1. If the values run away, try a different rearrangement. Some sequences are **periodic**: for example, uₙ₊₁ = (uₙ + 1)/(uₙ − 1) with u₁ = 3 gives 3, 2, 3, 2, … and never settles.' },
    practice(['Find the limit of `uₙ₊₁ = 0.5uₙ + 3`.', 'Find u₂, u₃ if `u₁ = 2` and `uₙ₊₁ = uₙ² − 1`.'], ['6', '3, 8']),
  ]),
  section('mixed', 'Revision & Question Library', 'Choose the right method, then try a mixed set.', [
    { h: 'Choose the method' },
    { table: [['Question clue', 'First step'], ['“common difference”', 'AP: uₙ = a + (n − 1)d and Sₙ = n/2[2a + (n − 1)d]'], ['“common ratio”', 'GP: uₙ = ar^(n − 1) and Sₙ = a(1 − rⁿ)/(1 − r)'], ['“sum to infinity”', 'Check |r| < 1, then a/(1 − r)'], ['“recurring decimal”', 'Write it as a GP and use S∞'], ['“show that Σ … = …”', 'Split, use the standard results, factorise'], ['“method of differences”', 'Partial fractions, write out terms, cancel'], ['“expand (a + bx)ⁿ”', 'n a whole number: Pascal or ⁿCᵣ. Otherwise take out a factor to get (1 + u)ⁿ'], ['“limit of the sequence”', 'Put uₙ = uₙ₊₁ = L and solve'], ['“root by iteration”', 'Rearrange to x = g(x); check a sign change first']] },
    practice(['The 3rd term of an AP is 10 and the 7th term is 22. Find the 20th term.', 'Find the sum to infinity of 18 − 6 + 2 − …', 'Find the coefficient of x³ in `(1 + 2x)^6`.', 'Find the limit of `uₙ₊₁ = 0.4uₙ + 3`.'], ['61', '27/2', '160', '5']),
    { c: true },
    { h: 'Mixed practice' },
    { p: 'Try the ten mixed questions below. They use different skills from this topic. Every card includes a worked answer. Click Show me working when you are ready.' },
    { diagram: 'sources' },
  ]),
];
