/**
 * Builds the Technical Drawing recording pack.
 *
 *   npx tsx scripts/build_drawing_scripts.mts
 *
 * The lessons themselves are the source of truth. This reads the topics listed
 * in `SCRIPTED` and writes two things from them:
 *
 *   scripts/narration/technical-drawing.captions.json  — what the caption
 *     generator measures each MP3 against
 *   docs/TECHNICAL_DRAWING_SCRIPTS.md                  — the blocks a human
 *     pastes into the voice generator
 *
 * Generating both from the lesson data is the whole point: a script that has
 * drifted from what the app displays makes the captions drift from the voice,
 * and that is invisible until somebody watches the finished clip. Add a topic
 * id to `SCRIPTED`, re-run this, record the clips, then run
 * `node scripts/generate_narration_captions.mjs scripts/narration/technical-drawing.captions.json`.
 */

import { writeFile } from 'node:fs/promises';
import { DRAW_TOPICS } from '../src/features/practicals/polytechnic/technical-drawing/drawingTopics';
import type { DrawStep, DrawTopic } from '../src/features/practicals/polytechnic/technical-drawing/drawingTopics';

/**
 * Every topic that is wired for voice, in the order it is taught. All of these
 * go into the captions script — a recorded clip whose entry is missing is a
 * clip the app cannot use, so this list only ever grows.
 */
const SCRIPTED = [
  'bisect-line',
  'perpendicular-on-line',
  'divide-line',
  'perpendicular-from-point',
  'parallel-lines',
  'bisect-angle',
  'angles-without-protractor',
  'copied-angle',
  'arc-centre',
  'geometric-shapes',
  'blend-arcs',
  'ellipse-and-scales',
  'orthographic',
  'isometric',
  'bars',
  'tubes',
  'shafts',
  'compression-springs',
  'tension-springs',
  'splined-shaft-external',
];

/**
 * The topics the recording document lists. Kept to whatever is being recorded
 * next, because the document is a worklist to read at a microphone — a hundred
 * blocks of already-recorded script get in the way of finding the one you want.
 * Everything in SCRIPTED stays wired whether it is listed here or not.
 */
const IN_DOC = [
  'blend-arcs',
  'ellipse-and-scales',
  'orthographic',
  'isometric',
  'bars',
  'tubes',
  'shafts',
  'compression-springs',
  'tension-springs',
  'splined-shaft-external',
];

const CAPTIONS_PATH = 'scripts/narration/technical-drawing.captions.json';
const DOC_PATH = 'docs/TECHNICAL_DRAWING_SCRIPTS.md';

/** One clip per step, named after the step, under the topic's own folder. */
const clipSrc = (topic: DrawTopic, step: DrawStep) =>
  `/sounds/technical-drawing/${topic.id}/${step.id}.mp3`;

/**
 * The pointing hand is driven by the caption track once a clip is recorded, so
 * a line that points at the sheet has to carry the same focus the estimated
 * track would have given it. Keep this in step with `timeStep()`.
 */
function focusFor(step: DrawStep, stepIndex: number, lineIndex: number) {
  const line = step.lines[lineIndex];
  if (!line.at) return undefined;
  return {
    sceneAnchor: 'focus',
    label: line.label ?? `${stepIndex + 1}.${lineIndex + 1}`,
  };
}

function topicsInOrder(ids: string[] = SCRIPTED): DrawTopic[] {
  return ids.map((id) => {
    const topic = DRAW_TOPICS.find((item) => item.id === id);
    if (!topic) throw new Error(`No topic with id "${id}"`);
    return topic;
  });
}

function buildCaptions() {
  return {
    output: 'src/lib/audio/narration/technicalDrawing.ts',
    exportName: 'DRAWING_NARRATION_TRACKS',
    title: 'Technical Drawing',
    clips: topicsInOrder().flatMap((topic) =>
      topic.steps.map((step, stepIndex) => ({
        src: clipSrc(topic, step),
        lines: step.lines.map((line, lineIndex) => {
          const focus = focusFor(step, stepIndex, lineIndex);
          return focus ? { text: line.text, focus } : { text: line.text };
        }),
      }))
    ),
  };
}

const header = (example: string) => `# Technical Drawing — voice recording scripts

<!-- GENERATED by scripts/build_drawing_scripts.mts — edit the lesson, not this file. -->

The lessons are the source of truth. Each \`####\` heading below is **one MP3** — copy its whole block and feed it
to your voice generator in one go. One clip is one step of the lesson, and the step ends when the clip ends, so a
clip is never split into several files.

## How to record and wire the voices in

1. Copy a block, generate the voice, and save it at the path in its heading, under \`public/sounds/technical-drawing/\`.
   So the first block below is saved as \`public/sounds/technical-drawing/${example}\`.
2. Leave the \`[pause]\` markers in. They are where the on-screen caption changes line, and the caption generator
   finds those silences in the finished MP3 with ffmpeg to line the words up with the voice.
   Aim for about half a second of silence at each one.
3. Run \`node scripts/generate_narration_captions.mjs scripts/narration/technical-drawing.captions.json\`.
   That measures every MP3 it can find and rewrites \`src/lib/audio/narration/technicalDrawing.ts\`.
4. That is all. The step retimes itself to the clip: the captions, the pointing hand and the pencil all follow the
   recorded voice, so a re-recorded take needs no code change.

A step whose clip has not been recorded yet falls back to estimated timings and runs silently, so a half-recorded
topic still plays end to end.

### Do not edit this file

It is generated from the lessons. To change what is said, change the topic in
\`src/features/practicals/polytechnic/technical-drawing/topicsConstructions.ts\` and run:

\`\`\`bash
npx tsx scripts/build_drawing_scripts.mts
\`\`\`

That rewrites this file and the captions script together, so the words the narrator reads can never drift from the
words the app shows. If they drift, the generator spreads the script across the wrong speech and the captions slide
out of time for the rest of the clip.

### Voice

Tinashe, the same instructor as the science practicals: unhurried, warm, speaking to somebody meeting a drawing
board for the first time. Short sentences. Read the numbers as words — "one hundred and forty", not "140".
`;

function buildDoc() {
  const first = topicsInOrder(IN_DOC)[0];
  const parts = [header(`${first.id}/${first.steps[0].id}.mp3`)];

  for (const topic of topicsInOrder(IN_DOC)) {
    const folder = `public/sounds/technical-drawing/${topic.id}/`;
    parts.push(
      '',
      '---',
      '',
      `## ${topic.title}`,
      '',
      `_Topic id \`${topic.id}\` · ${topic.steps.length} steps · folder \`${folder}\`_`,
      ''
    );

    for (const step of topic.steps) {
      parts.push(`#### \`${topic.id}/${step.id}.mp3\` — ${step.title}`, '');
      parts.push('```text');
      parts.push(step.lines.map((line) => line.text).join(' [pause]\n'));
      parts.push('```', '');
    }
  }

  const remaining = DRAW_TOPICS.length - SCRIPTED.length;
  parts.push(
    '---',
    '',
    '## What is not in this file',
    '',
    `${SCRIPTED.length} of the ${DRAW_TOPICS.length} topics in the studio are wired for voice; ${remaining} still to write.`,
    'This file lists only the ones being recorded now — see `IN_DOC` in `scripts/build_drawing_scripts.mts`.',
    'The rest stay wired and keep playing; their scripts are in the git history of this file.',
    '',
    'To take the next topic on, add its id to `SCRIPTED` and `IN_DOC` and run the script again.',
    'The clip path is always `/sounds/technical-drawing/<topic id>/<step id>.mp3`, built from those two ids in',
    '`narrationSrc()`, so nothing has to be registered anywhere else.',
    ''
  );

  return parts.join('\n');
}

const captions = buildCaptions();
await writeFile(CAPTIONS_PATH, `${JSON.stringify(captions, null, 2)}\n`, 'utf8');
await writeFile(DOC_PATH, buildDoc(), 'utf8');

const steps = captions.clips.length;
const docSteps = topicsInOrder(IN_DOC).reduce((sum, topic) => sum + topic.steps.length, 0);
console.log(`${CAPTIONS_PATH}  (${SCRIPTED.length} topics wired, ${steps} clips)`);
console.log(`${DOC_PATH}  (${IN_DOC.length} topics listed, ${docSteps} recording blocks)`);
