#!/usr/bin/env node
/**
 * Turns the Teach Me lesson JSON into the two things the voice work needs:
 *
 *   1. scripts/narration/sql-lessons.captions.json — the input for
 *      scripts/generate_narration_captions.mjs, which measures the recorded
 *      MP3s and produces src/lib/audio/narration/sqlLessons.ts.
 *   2. docs/SQL_TEACH_ME_SCRIPTS.md — the recording sheet: every clip, its
 *      filename, and the exact words to say, in order.
 *
 *   node scripts/build_sql_lesson_captions.mjs
 *
 * The lesson JSON under src/features/courses/polytechnic/nc-it/database-concepts/teach-me/
 * is the single source of truth. Edit a line there and re-run this, so the app,
 * the captions and the recording sheet can never drift apart.
 */

import { access, readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const LESSON_DIR = join(ROOT, "src/features/courses/polytechnic/nc-it/database-concepts/teach-me");
const CAPTIONS_OUT = join(ROOT, "scripts/narration/sql-lessons.captions.json");
const DOC_OUT = join(ROOT, "docs/SQL_TEACH_ME_SCRIPTS.md");
const AUDIO_DIR = "public/sounds/sql-lessons";
/**
 * Written between the script lines of a clip. Most text-to-speech tools take
 * this as an instruction to stop talking for a moment; the caption generator
 * then finds that silence in the finished MP3 and starts the next caption line
 * on it. If a tool reads the marker out loud instead, change it here to
 * whatever that tool understands (`<break time="500ms"/>`, `...`) and re-run.
 */
const PAUSE_MARKER = "[pause]";
/** Formats a clip may arrive in, in the order they are looked for. Mirrors CLIP_EXTENSIONS. */
const CLIP_EXTENSIONS = ["mp3", "wav", "ogg", "m4a"];

/**
 * The clip file that actually exists for a step, so the caption generator
 * measures the recording that is there rather than the one we assumed. Falls
 * back to .mp3 for steps that have not been voiced yet.
 */
async function clipSrc(lessonId, stepId) {
  for (const extension of CLIP_EXTENSIONS) {
    const src = `/sounds/sql-lessons/${lessonId}/${stepId}.${extension}`;
    try {
      await access(join(ROOT, "public", src.replace(/^\//, "")));
      return src;
    } catch {
      /* not this format — try the next */
    }
  }
  return `/sounds/sql-lessons/${lessonId}/${stepId}.mp3`;
}

async function loadChapters() {
  const files = (await readdir(LESSON_DIR)).filter((name) => name.endsWith(".json")).sort();
  const chapters = [];
  for (const file of files) {
    chapters.push(JSON.parse(await readFile(join(LESSON_DIR, file), "utf8")));
  }
  return chapters;
}

/** Rough spoken length, matching src/lib/audio/narrationEstimate.ts closely enough to plan a session. */
function estimateSeconds(lines) {
  const words = lines.reduce((sum, line) => sum + line.text.split(/\s+/).filter(Boolean).length, 0);
  return Math.round(words / 2.3);
}

function formatDuration(seconds) {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}m ${String(secs).padStart(2, "0")}s`;
}

const chapters = await loadChapters();

/* ---- 1. the caption-generator input ---- */

const clips = [];
for (const chapter of chapters) {
  for (const lesson of chapter.lessons) {
    for (const step of lesson.steps) {
      clips.push({
        src: await clipSrc(lesson.id, step.id),
        lines: step.lines.map((line) => (line.focus ? { text: line.text, focus: { selector: line.focus } } : { text: line.text })),
      });
    }
  }
}

await mkdir(dirname(CAPTIONS_OUT), { recursive: true });
await writeFile(
  CAPTIONS_OUT,
  `${JSON.stringify(
    {
      output: "src/lib/audio/narration/sqlLessons.ts",
      exportName: "SQL_LESSON_NARRATION_TRACKS",
      title: "SQL Teach Me",
      clips,
    },
    null,
    2,
  )}\n`,
  "utf8",
);

/* ---- 2. the recording sheet ---- */

let totalSeconds = 0;
const doc = [];
doc.push("# SQL Teach Me — voice recording scripts");
doc.push("");
doc.push("<!-- GENERATED by scripts/build_sql_lesson_captions.mjs — edit the lesson JSON, not this file. -->");
doc.push("");
doc.push(
  "Source of truth: `src/features/courses/polytechnic/nc-it/database-concepts/teach-me/*.json`. " +
    "Each `####` heading below is **one MP3** — copy its whole block and feed it to your voice generator in one go. " +
    "The lesson advances when the clip ends, so a clip is never split into several files.",
);
doc.push("");
doc.push("## How to record and wire the voices in");
doc.push("");
doc.push(`1. Copy a block, generate the voice, and save it at the path in its heading, under \`${AUDIO_DIR}/\`.`);
doc.push(
  `   The headings say \`.mp3\`, but ${CLIP_EXTENSIONS.map((e) => `\`.${e}\``).join(", ")} all work — ` +
    "save whatever your generator produces and the player finds it.",
);
doc.push(
  `2. Leave the \`${PAUSE_MARKER}\` markers in. They are where the on-screen caption changes line, and the caption ` +
    "generator finds those silences in the finished MP3 with ffmpeg to line the words up with the voice.",
);
doc.push(
  "   Aim for about half a second of silence at each one. If your tool reads the marker out loud instead of pausing, " +
    "swap it for whatever that tool understands — set `PAUSE_MARKER` in `scripts/build_sql_lesson_captions.mjs` and re-run.",
);
doc.push("3. Run `node scripts/generate_narration_captions.mjs scripts/narration/sql-lessons.captions.json`.");
doc.push("   That measures every MP3 and rewrites `src/lib/audio/narration/sqlLessons.ts`.");
doc.push("4. That is all. The lesson retimes itself: captions, the typing of the SQL and the moment Run is pressed all");
doc.push("   follow the recorded clip, so a re-recorded take needs no code change.");
doc.push("");
doc.push("Clips that have not been recorded yet fall back to estimated timings, so a half-finished course still runs — silently.");
doc.push("");
doc.push("### Cues");
doc.push("");
doc.push("Some steps name a **type cue** and a **run cue**. Those are phrases taken from the script itself: the SQL starts");
doc.push("typing when the narrator reaches the type cue, and Run is pressed at the run cue.");
doc.push("");
doc.push("Steps marked **whiteboard** draw a diagram over the console instead of running SQL, and each drawing appears on a");
doc.push("phrase from the script in the same way.");
doc.push("");
doc.push("So: keep every line word for word. A changed phrase does not break anything — the cue just falls back to a rough");
doc.push("position in the clip — but the timing stops being exact.");
doc.push("");

for (const [chapterIndex, chapter] of chapters.entries()) {
  doc.push(`## Chapter ${chapterIndex + 1} — ${chapter.title}`);
  doc.push("");
  doc.push(`_${chapter.subtitle}_`);
  doc.push("");

  for (const [lessonIndex, lesson] of chapter.lessons.entries()) {
    const lessonSeconds = lesson.steps.reduce((sum, step) => sum + estimateSeconds(step.lines), 0);
    totalSeconds += lessonSeconds;
    doc.push(`### ${chapterIndex + 1}.${lessonIndex + 1} ${lesson.title}`);
    doc.push("");
    doc.push(`- Folder: \`${AUDIO_DIR}/${lesson.id}/\``);
    doc.push(`- ${lesson.steps.length} clips, roughly ${formatDuration(lessonSeconds)} of speech`);
    doc.push(`- Exam note shown on screen: ${lesson.examTip}`);
    doc.push("");

    for (const step of lesson.steps) {
      doc.push(`#### \`${lesson.id}/${step.id}.mp3\` — ${step.title}`);
      doc.push("");
      const flags = [];
      if (step.typeCue) flags.push(`type cue: “${step.typeCue}”`);
      if (step.runCue) flags.push(`run cue: “${step.runCue}”`);
      if (step.serverOnly) flags.push("not executed (MySQL-only)");
      if (step.expectError) flags.push("fails on purpose");
      if (step.board) flags.push(`whiteboard: ${step.board.items.length} drawings appear during this clip`);
      if (flags.length) {
        doc.push(`> ${flags.join(" · ")}`);
        doc.push("");
      }
      // One copy-paste block per clip: the whole script, with an explicit
      // [pause] wherever the caption bar needs to change line. The generator
      // finds those pauses in the recording and lines the captions up with them.
      doc.push("```text");
      step.lines.forEach((line, index) => {
        doc.push(index === step.lines.length - 1 ? line.text : `${line.text} ${PAUSE_MARKER}`);
      });
      doc.push("```");
      doc.push("");
      if (step.sql) {
        doc.push("```sql");
        doc.push(step.sql);
        doc.push("```");
        doc.push("");
      }
    }
  }
}

doc.push("---");
doc.push("");
doc.push(`**Totals:** ${clips.length} clips, roughly ${formatDuration(totalSeconds)} of speech across the whole course.`);
doc.push("");

await mkdir(dirname(DOC_OUT), { recursive: true });
await writeFile(DOC_OUT, `${doc.join("\n")}`, "utf8");

console.log(`Wrote ${CAPTIONS_OUT} (${clips.length} clips)`);
console.log(`Wrote ${DOC_OUT} (~${formatDuration(totalSeconds)} of speech)`);

/* ---- 3. shout about recordings the app will never find ---- */

/**
 * The player looks a clip up by `<lesson-id>/<step-id>.<ext>` and nothing else,
 * so a recording saved as `add_column.mp3` for the step `add-column` is simply
 * never heard — no error, no warning, just silence over a lesson that looks
 * finished. That has happened once, to nineteen clips at a time, so check for
 * it here where the expected names are already known.
 */
const expected = new Set(clips.map((clip) => clip.src.replace(/\.[^.]+$/, "")));
const strays = [];

for (const lessonId of await readdir(join(ROOT, AUDIO_DIR), { withFileTypes: true })) {
  if (!lessonId.isDirectory()) continue;
  for (const file of await readdir(join(ROOT, AUDIO_DIR, lessonId.name))) {
    const match = file.match(/^(.*)\.([^.]+)$/);
    if (!match || !CLIP_EXTENSIONS.includes(match[2].toLowerCase())) continue;
    const base = `/sounds/sql-lessons/${lessonId.name}/${match[1]}`;
    if (expected.has(base)) continue;
    const suggestion = match[1].replace(/_/g, "-");
    const fix = expected.has(`/sounds/sql-lessons/${lessonId.name}/${suggestion}`)
      ? ` → rename to ${suggestion}.${match[2]}`
      : " (no step of that name in the lesson JSON)";
    strays.push(`  ${lessonId.name}/${file}${fix}`);
  }
}

/* ---- 4. shout about cues the narrator never actually says ---- */

/**
 * `typeCue`, `runCue` and every `marks[].cue` are looked up by searching the
 * clip's own script. A cue that appears nowhere in the lines silently falls back
 * to a guessed millisecond offset, which is how you end up with the editor
 * typing while the narrator is still explaining. Catch it here instead.
 */
const norm = (text) =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9*_\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const unspoken = [];
for (const chapter of chapters) {
  for (const lesson of chapter.lessons) {
    for (const step of lesson.steps) {
      const script = step.lines.map((line) => norm(line.text));
      const spoken = (cue) => {
        const needle = norm(cue);
        return script.some(
          (line) =>
            line === needle ||
            line.startsWith(`${needle} `) ||
            line.endsWith(` ${needle}`) ||
            line.includes(` ${needle} `)
        );
      };
      for (const [kind, cue] of [
        ["typeCue", step.typeCue],
        ["runCue", step.runCue],
        ...(step.marks ?? []).map((mark) => ["mark", mark.cue]),
      ]) {
        if (cue && !spoken(cue)) unspoken.push(`  ${lesson.id}/${step.id} [${kind}] ${JSON.stringify(cue)}`);
      }
    }
  }
}

if (unspoken.length > 0) {
  console.warn(`\n⚠  ${unspoken.length} cue(s) are never spoken in their own clip, so they will fire at a guessed time:`);
  console.warn(unspoken.join("\n"));
  console.warn("\nA cue must be a phrase from that step's own lines, matched on whole words.");
  process.exitCode = 1;
}

if (strays.length > 0) {
  console.warn(`\n⚠  ${strays.length} recording(s) will never be played — the filename is not a step id:`);
  console.warn(strays.join("\n"));
  console.warn("\nStep ids use hyphens, never underscores. Fix the names, then re-run this script.");
  process.exitCode = 1;
}
