import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');
const SITE_URL = 'https://www.examsidemann.com';
const indexHtml = await readFile(path.join(DIST, 'index.html'), 'utf8');
const sitemap = await readFile(path.join(DIST, 'sitemap.xml'), 'utf8');

const builtAssets = [
  ...indexHtml.matchAll(/(?:src|href)="(\/assets\/[^"]+)"/g),
].map((match) => match[1]);
const assetEntries = await readdir(path.join(DIST, 'assets'), {
  withFileTypes: true,
});
const builtCodeAssets = assetEntries
  .filter((entry) => entry.isFile() && /\.(?:css|js)$/.test(entry.name))
  .map((entry) => `/assets/${entry.name}`)
  .sort();

const collectFiles = async (directory) => {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collectFiles(entryPath));
    if (entry.isFile()) files.push(entryPath);
  }
  return files;
};

const toPublicUrl = (filePath) => `/${path.relative(DIST, filePath)
  .split(path.sep)
  .map(encodeURIComponent)
  .join('/')}`;

const publicPages = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)]
  .map((match) => new URL(match[1]))
  .filter((url) => url.origin === SITE_URL)
  .map((url) => `${url.pathname}${url.search}`);

const coreAssets = [
  '/',
  '/index.html',
  '/offline.html',
  '/site.webmanifest',
  '/favicon-48.png',
  '/apple-touch-icon.png',
  '/app-icon-192.png',
  '/app-icon-512.png',
  '/app-icon-maskable-512.png',
  '/qpandbooks.json',
  ...builtAssets,
];
const coreAssetSet = new Set(coreAssets);
const warmCodeAssets = builtCodeAssets.filter((url) => !coreAssetSet.has(url));
const warmCodeAssetSet = new Set(warmCodeAssets);
const generatedFiles = await collectFiles(DIST);
const hashFile = (filePath) => new Promise((resolve, reject) => {
  const hash = createHash('sha256');
  const stream = createReadStream(filePath);
  stream.on('data', (chunk) => hash.update(chunk));
  stream.on('error', reject);
  stream.on('end', () => resolve(hash.digest('hex').slice(0, 16)));
});
const offlineLibraryEntries = [];
for (const filePath of generatedFiles) {
  const url = toPublicUrl(filePath);
  if (
    url.endsWith('.html') ||
    ['/service-worker.js', '/sitemap.xml', '/robots.txt', '/_redirects'].includes(url) ||
    coreAssetSet.has(url) ||
    warmCodeAssetSet.has(url)
  ) continue;
  offlineLibraryEntries.push({
    url,
    size: (await stat(filePath)).size,
    revision: await hashFile(filePath),
  });
}
offlineLibraryEntries.sort((left, right) => left.url.localeCompare(right.url));
const offlineLibraryBytes = offlineLibraryEntries.reduce((total, entry) => total + entry.size, 0);

const version = createHash('sha256')
  .update(indexHtml)
  .update(sitemap)
  .update(JSON.stringify(coreAssets))
  .update(JSON.stringify(warmCodeAssets))
  .update(JSON.stringify(offlineLibraryEntries))
  .digest('hex')
  .slice(0, 12);

const serviceWorker = `/* Generated by scripts/generateServiceWorker.mjs. */
const VERSION = ${JSON.stringify(version)};
const CACHE_PREFIX = "exam-sidemann-";
const CACHE_NAMES = {
  precache: \`\${CACHE_PREFIX}precache-\${VERSION}\`,
  pages: \`\${CACHE_PREFIX}pages-\${VERSION}\`,
  assets: \`\${CACHE_PREFIX}assets-\${VERSION}\`,
  media: \`\${CACHE_PREFIX}media-\${VERSION}\`,
  external: \`\${CACHE_PREFIX}external-\${VERSION}\`,
  library: \`\${CACHE_PREFIX}library-v1\`,
};
const CURRENT_CACHES = new Set(Object.values(CACHE_NAMES));
const CORE_ASSETS = ${JSON.stringify([...new Set(coreAssets)], null, 2)};
const WARM_CODE_ASSETS = ${JSON.stringify(warmCodeAssets, null, 2)};
const WARM_PAGES = ${JSON.stringify([...new Set(publicPages)], null, 2)};
const OFFLINE_LIBRARY = ${JSON.stringify(offlineLibraryEntries, null, 2)};
const OFFLINE_LIBRARY_BYTES = ${offlineLibraryBytes};
const EXTERNAL_ASSETS = [
  "https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp",
  "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=Nunito:wght@300;400;600;700;800&display=swap",
];
const CACHE_LIMITS = {
  pages: ${Math.max(600, publicPages.length + 40)},
  assets: ${Math.max(800, warmCodeAssets.length + 200)},
  media: ${Math.max(1600, offlineLibraryEntries.length + 200)},
  external: 1600,
};

const isCacheable = (response) =>
  Boolean(response) && (response.ok || response.type === "opaque");

async function trimCache(cacheName, maxEntries) {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  const overflow = keys.length - maxEntries;
  if (overflow <= 0) return;
  await Promise.all(keys.slice(0, overflow).map((key) => cache.delete(key)));
}

async function putInCache(cacheName, request, response, maxEntries) {
  if (!isCacheable(response)) return;
  const cache = await caches.open(cacheName);
  await cache.put(request, response.clone());
  if (maxEntries) {
    await trimCache(cacheName, maxEntries);
  }
}

async function cacheCoreAssets() {
  const cache = await caches.open(CACHE_NAMES.precache);
  await Promise.all(
    CORE_ASSETS.map(async (url) => {
      const request = new Request(url, { cache: "reload" });
      const response = await fetch(request);
      if (!response.ok) {
        throw new Error(\`Unable to precache \${url}: \${response.status}\`);
      }
      await cache.put(request, response);
    }),
  );
}

async function cacheInBatches(urls, cacheName, options = {}) {
  const cache = await caches.open(cacheName);
  const batchSize = 6;
  let failed = 0;

  for (let index = 0; index < urls.length; index += batchSize) {
    const batch = urls.slice(index, index + batchSize);
    const results = await Promise.allSettled(
      batch.map(async (url) => {
        const request = new Request(url, options);
        const response = await fetch(request);
        if (!isCacheable(response)) throw new Error(\`Unable to cache \${url}\`);
        await cache.put(request, response);
      }),
    );
    failed += results.filter((result) => result.status === "rejected").length;
  }
  if (failed > 0) throw new Error(\`\${failed} offline resources could not be cached\`);
}

async function notifyClients(message) {
  const clients = await self.clients.matchAll({ type: "window" });
  clients.forEach((client) => client.postMessage(message));
}

async function cacheOfflineLibrary() {
  await ensureOfflineCache();
  const libraryCache = await caches.open(CACHE_NAMES.library);
  const manifestRequest = new Request('/__exam-sidemann-library-manifest__');
  const previousManifestResponse = await libraryCache.match(manifestRequest, { ignoreVary: true });
  const previousManifest = await previousManifestResponse?.json().catch(() => undefined);
  if (previousManifest?.version === VERSION) {
    await notifyClients({
      type: "OFFLINE_LIBRARY_READY",
      version: VERSION,
      assetCount: OFFLINE_LIBRARY.length,
      bytes: OFFLINE_LIBRARY_BYTES,
    });
    return;
  }

  try {
    const previousRevisions = new Map(
      Array.isArray(previousManifest?.entries)
        ? previousManifest.entries.map((entry) => [entry.url, entry.revision])
        : [],
    );
    const pendingEntries = OFFLINE_LIBRARY.filter(
      (entry) => previousRevisions.get(entry.url) !== entry.revision,
    );
    const pendingBytes = pendingEntries.reduce((total, entry) => total + entry.size, 0);
    const estimate = await self.navigator.storage?.estimate?.();
    const available = estimate?.quota && typeof estimate.usage === "number"
      ? estimate.quota - estimate.usage
      : undefined;
    // Leave headroom for IndexedDB, browser accounting overhead and future lesson updates.
    if (available !== undefined && available < pendingBytes * 1.15) {
      await notifyClients({
        type: "OFFLINE_LIBRARY_UNAVAILABLE",
        reason: "insufficient-storage",
        requiredBytes: pendingBytes,
        availableBytes: available,
      });
      return;
    }

    let completed = OFFLINE_LIBRARY.length - pendingEntries.length;
    let failed = 0;
    const batchSize = 4;
    for (let index = 0; index < pendingEntries.length; index += batchSize) {
      const batch = pendingEntries.slice(index, index + batchSize);
      const results = await Promise.allSettled(batch.map(async ({ url }) => {
        const request = new Request(url, { cache: "reload", credentials: "same-origin" });
        const response = await fetch(request);
        if (!isCacheable(response)) throw new Error(\`Unable to cache \${url}\`);
        await libraryCache.put(request, response);
      }));
      completed += results.filter((result) => result.status === "fulfilled").length;
      failed += results.filter((result) => result.status === "rejected").length;
      await notifyClients({
        type: "OFFLINE_LIBRARY_PROGRESS",
        completed,
        failed,
        total: OFFLINE_LIBRARY.length,
        bytes: OFFLINE_LIBRARY_BYTES,
      });
    }

    if (failed > 0) {
      await notifyClients({
        type: "OFFLINE_LIBRARY_INCOMPLETE",
        completed,
        failed,
        total: OFFLINE_LIBRARY.length,
      });
      return;
    }

    const currentUrls = new Set(OFFLINE_LIBRARY.map((entry) => new URL(entry.url, self.location.origin).href));
    const oldRequests = await libraryCache.keys();
    await Promise.all(oldRequests
      .filter((request) => request.url !== manifestRequest.url && !currentUrls.has(request.url))
      .map((request) => libraryCache.delete(request)));
    await libraryCache.put(manifestRequest, new Response(JSON.stringify({
      version: VERSION,
      ready: true,
      assetCount: OFFLINE_LIBRARY.length,
      bytes: OFFLINE_LIBRARY_BYTES,
      entries: OFFLINE_LIBRARY.map(({ url, revision }) => ({ url, revision })),
    }), { headers: { "Content-Type": "application/json" } }));
    await notifyClients({
      type: "OFFLINE_LIBRARY_READY",
      version: VERSION,
      assetCount: OFFLINE_LIBRARY.length,
      bytes: OFFLINE_LIBRARY_BYTES,
    });
  } catch (error) {
    await notifyClients({
      type: "OFFLINE_LIBRARY_UNAVAILABLE",
      reason: error?.name === "QuotaExceededError" ? "insufficient-storage" : "download-failed",
    });
  }
}

async function warmOfflineCache() {
  const markerRequest = new Request(
    \`/__exam-sidemann-offline-ready__/\${VERSION}\`,
  );
  const precache = await caches.open(CACHE_NAMES.precache);
  const isAlreadyWarm = await precache.match(markerRequest, {
    ignoreVary: true,
  });
  if (isAlreadyWarm) {
    return;
  }

  await Promise.all([
    cacheInBatches(WARM_PAGES, CACHE_NAMES.pages, {
      cache: "reload",
      credentials: "same-origin",
      headers: { Accept: "text/html" },
    }),
    cacheInBatches(WARM_CODE_ASSETS, CACHE_NAMES.assets, {
      cache: "reload",
      credentials: "same-origin",
    }),
    cacheInBatches(EXTERNAL_ASSETS, CACHE_NAMES.external, {
      cache: "reload",
      mode: "no-cors",
    }),
  ]);
  await precache.put(
    markerRequest,
    new Response(JSON.stringify({ version: VERSION, ready: true }), {
      headers: { "Content-Type": "application/json" },
    }),
  );

  await notifyClients({
    type: "OFFLINE_CACHE_READY",
    version: VERSION,
    pageCount: WARM_PAGES.length,
    codeAssetCount: WARM_CODE_ASSETS.length,
  });
}

let offlineWarmPromise;
let libraryWarmPromise;
const ensureOfflineCache = () => {
  offlineWarmPromise ||= warmOfflineCache().catch((error) => {
    offlineWarmPromise = undefined;
    throw error;
  });
  return offlineWarmPromise;
};
const ensureOfflineLibrary = () => {
  libraryWarmPromise ||= cacheOfflineLibrary().catch((error) => {
    libraryWarmPromise = undefined;
    throw error;
  });
  return libraryWarmPromise;
};

async function networkFirstPage(request) {
  const cache = await caches.open(CACHE_NAMES.pages);
  const cached =
    (await cache.match(request, {
      ignoreSearch: true,
      ignoreVary: true,
    })) ||
    (await caches.match(request, {
      ignoreSearch: true,
      ignoreVary: true,
    }));
  const controller = new AbortController();
  const timeout = setTimeout(
    () => controller.abort(),
    cached ? 1_500 : 4_500,
  );

  try {
    const response = await fetch(
      new Request(request, { signal: controller.signal }),
    );
    if (response.ok) {
      await cache.put(request, response.clone());
      void trimCache(CACHE_NAMES.pages, CACHE_LIMITS.pages);
      return response;
    }
    if (response.status >= 500) {
      if (cached) return cached;
      const appShell =
        (await caches.match("/index.html", { ignoreVary: true })) ||
        (await caches.match("/offline.html", { ignoreVary: true }));
      if (appShell) return appShell;
    }
    return response;
  } catch {
    if (cached) return cached;

    return (
      (await caches.match("/index.html", { ignoreVary: true })) ||
      (await caches.match("/offline.html", { ignoreVary: true })) ||
      new Response("Exam Sidemann is offline.", {
        status: 503,
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      })
    );
  } finally {
    clearTimeout(timeout);
  }
}

async function cacheFirst(request, cacheName, maxEntries) {
  const cached = await caches.match(request, { ignoreVary: true });
  if (cached) return cached;

  const response = await fetch(request);
  if (isCacheable(response)) {
    await putInCache(cacheName, request, response, maxEntries);
  }
  return response;
}

async function networkFirstData(request) {
  const cache = await caches.open(CACHE_NAMES.assets);
  const cached = await cache.match(request, { ignoreVary: true });
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), cached ? 2_000 : 5_000);

  try {
    const response = await fetch(new Request(request, {
      cache: "no-cache",
      signal: controller.signal,
    }));
    if (isCacheable(response)) {
      await cache.put(request, response.clone());
    }
    return response;
  } catch {
    return cached || new Response("{}", {
      status: 503,
      headers: { "Content-Type": "application/json" },
    });
  } finally {
    clearTimeout(timeout);
  }
}

async function cacheFirstMedia(request) {
  const cached = await caches.match(request, { ignoreVary: true });
  if (cached) {
    const cachedType = cached.headers.get("content-type") || "";
    if (cachedType.startsWith("image/") || cachedType.startsWith("audio/") || cachedType.startsWith("video/") || cachedType.startsWith("font/")) {
      return cached;
    }
    const owningCache = await caches.open(CACHE_NAMES.media);
    await owningCache.delete(request);
  }

  const response = await fetch(request);
  const contentType = response.headers.get("content-type") || "";
  const validMedia = contentType.startsWith("image/") || contentType.startsWith("audio/") || contentType.startsWith("video/") || contentType.startsWith("font/");
  if (isCacheable(response) && validMedia) {
    await putInCache(CACHE_NAMES.media, request, response, CACHE_LIMITS.media);
  }
  return response;
}

async function staleWhileRevalidate(event, request, cacheName, maxEntries) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request, { ignoreVary: true });
  const network = fetch(request)
    .then(async (response) => {
      if (isCacheable(response)) {
        await putInCache(cacheName, request, response, maxEntries);
      }
      return response;
    })
    .catch(() => cached);

  if (cached) {
    event.waitUntil(network);
    return cached;
  }

  return (
    (await network) ||
    new Response("", {
      status: 504,
      statusText: "Offline",
    })
  );
}

async function rangeResponse(request) {
  let cached = await caches.match(request.url, { ignoreVary: true });

  // Browsers commonly request audio/video with a Range header on the very
  // first play. Fetch and retain the complete same-origin file once, then
  // serve the requested slice. That makes media which has been played online
  // remain usable after the browser or phone restarts.
  if (!cached || cached.type === "opaque") {
    const fullHeaders = new Headers(request.headers);
    fullHeaders.delete("range");
    const fullRequest = new Request(request.url, {
      headers: fullHeaders,
      credentials: request.credentials,
      cache: "no-cache",
    });
    const fullResponse = await fetch(fullRequest);
    const contentType = fullResponse.headers.get("content-type") || "";
    const validMedia = contentType.startsWith("audio/") || contentType.startsWith("video/");
    if (!isCacheable(fullResponse) || !validMedia) return fetch(request);

    await putInCache(CACHE_NAMES.media, fullRequest, fullResponse.clone(), CACHE_LIMITS.media);
    cached = fullResponse;
  }

  const rangeHeader = request.headers.get("range");
  const rangeMatch = rangeHeader?.match(/bytes=(\\d*)-(\\d*)/);
  if (!rangeMatch) return cached;

  const body = await cached.arrayBuffer();
  const start = rangeMatch[1] ? Number(rangeMatch[1]) : 0;
  const requestedEnd = rangeMatch[2] ? Number(rangeMatch[2]) : body.byteLength - 1;
  const end = Math.min(requestedEnd, body.byteLength - 1);

  if (start > end || start >= body.byteLength) {
    return new Response(null, {
      status: 416,
      headers: { "Content-Range": \`bytes */\${body.byteLength}\` },
    });
  }

  const headers = new Headers(cached.headers);
  headers.set("Accept-Ranges", "bytes");
  headers.set("Content-Range", \`bytes \${start}-\${end}/\${body.byteLength}\`);
  headers.set("Content-Length", String(end - start + 1));

  return new Response(body.slice(start, end + 1), {
    status: 206,
    statusText: "Partial Content",
    headers,
  });
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      await cacheCoreAssets();
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const cacheKeys = await caches.keys();
      await Promise.all(
        cacheKeys
          .filter(
            (key) => key.startsWith(CACHE_PREFIX) && !CURRENT_CACHES.has(key),
          )
          .map((key) => caches.delete(key)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    event.waitUntil(self.skipWaiting());
  }
  if (event.data?.type === "WARM_OFFLINE_CACHE") {
    event.waitUntil(ensureOfflineCache());
  }
  if (event.data?.type === "DOWNLOAD_OFFLINE_LIBRARY") {
    event.waitUntil(ensureOfflineLibrary());
  }
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  const isSameOrigin = url.origin === self.location.origin;

  if (isSameOrigin && url.pathname.startsWith("/api/")) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirstPage(request));
    return;
  }

  if (
    request.headers.has("range") &&
    isSameOrigin &&
    (request.destination === "audio" || request.destination === "video")
  ) {
    event.respondWith(rangeResponse(request));
    return;
  }

  if (isSameOrigin && url.pathname.startsWith("/assets/")) {
    event.respondWith(
      cacheFirst(request, CACHE_NAMES.assets, CACHE_LIMITS.assets),
    );
    return;
  }

  if (
    isSameOrigin &&
    ["image", "audio", "video", "font"].includes(request.destination)
  ) {
    event.respondWith(cacheFirstMedia(request));
    return;
  }

  if (
    isSameOrigin &&
    ["script", "style", "manifest"].includes(request.destination)
  ) {
    event.respondWith(
      staleWhileRevalidate(
        event,
        request,
        CACHE_NAMES.assets,
        CACHE_LIMITS.assets,
      ),
    );
    return;
  }

  if (
    isSameOrigin &&
    url.pathname.endsWith(".json")
  ) {
    event.respondWith(networkFirstData(request));
    return;
  }

  if (
    isSameOrigin &&
    request.destination === ""
  ) {
    event.respondWith(
      staleWhileRevalidate(
        event,
        request,
        CACHE_NAMES.assets,
        CACHE_LIMITS.assets,
      ),
    );
    return;
  }

  const cacheableExternalHosts = new Set([
    "cdn.tailwindcss.com",
    "fonts.googleapis.com",
    "fonts.gstatic.com",
    "aistudiocdn.com",
    "esm.sh",
    "drive.google.com",
    "lh3.googleusercontent.com",
    "tile.openstreetmap.org",
    "a.tile.openstreetmap.org",
    "b.tile.openstreetmap.org",
    "c.tile.openstreetmap.org",
  ]);
  if (!isSameOrigin && cacheableExternalHosts.has(url.hostname)) {
    event.respondWith(
      staleWhileRevalidate(
        event,
        request,
        CACHE_NAMES.external,
        CACHE_LIMITS.external,
      ),
    );
  }
});
`;

await writeFile(path.join(DIST, 'service-worker.js'), serviceWorker);

console.log(
  `Generated service worker ${version} with ${coreAssets.length} core assets, ${warmCodeAssets.length} background code assets, ${publicPages.length} warm pages, and ${offlineLibraryEntries.length} full-library assets (${(offlineLibraryBytes / 1024 / 1024).toFixed(1)} MiB).`,
);
