import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const root = process.cwd();
const base = 'public/sounds/ecd';
const assets = {};
function scan(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const file = `${dir}/${entry.name}`;
    if (entry.isDirectory()) scan(file);
    else if (/\.(mp3|wav)$/i.test(file)) {
      const url = '/' + file.replace(/^public\//, '');
      const key = url.replace(/\.(mp3|wav)$/i, '');
      if (!assets[key] || /\.wav$/i.test(url)) assets[key] = url;
    }
  }
}
scan(base);
fs.writeFileSync('src/data/ecdAudioAssets.json', JSON.stringify(assets, null, 2) + '\n');
// These data-only modules have no runtime imports. Transpile to keep the recording
// sheet tied to precisely the same wording and IDs that the games use.
async function data(file) {
  const source = fs.readFileSync(path.join(root, file), 'utf8');
  const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
  return import('data:text/javascript;base64,' + Buffer.from(js).toString('base64'));
}
const rows = [];
const add = (file, script) => rows.push({ file: `${base}/${file}`, script });
const games = await data('src/features/ecd/maths/gameData.ts');
for (const [prefix, folder] of Object.entries({ PRESENT:'present-count', STAR:'star-wish', TRACE:'trace-numbers', WAKE:'wake-up', SUBITISE:'subitise', HOP:'one-more', COUNTBACK:'count-back', CAVE:'cave-add', FRAME:'ten-frame', POSITION:'above-below' })) {
  add(`maths/${folder}/intro.wav`, games[`${prefix}_INTRO`]);
  for (const round of games[`${prefix}_ROUNDS`]) {
    add(`maths/${folder}/${round.id}.wav`, round.script);
    add(`maths/${folder}/prompts/${round.id}.wav`, round.prompt);
  }
}
const monsters = await data('src/features/ecd/maths/monsterMathsData.ts');
for (const operation of ['addition', 'subtraction']) {
  add(`maths/${operation}/intro.wav`, monsters.MONSTER_INTROS[operation]);
  for (const [id, script] of Object.entries(monsters.MONSTER_FEEDBACK)) add(`maths/${operation}/${id}.wav`, script);
  for (const round of monsters.monsterRounds(operation)) add(`maths/${operation}/prompts/${round.id}.wav`, round.script);
}
const phonics = await data('src/features/ecd/reading/phonicsAlphabet.ts');
for (const letter of phonics.PHONICS_ALPHABET) {
  add(phonics.phonicsLetterVoiceUrl(letter.letter).replace('/sounds/ecd/', '').replace('.mp3', '.wav'), letter.script);
  add(phonics.phonicsPromptVoiceUrl(letter.letter).replace('/sounds/ecd/', '').replace('.mp3', '.wav'), letter.prompt);
}
const rhymes = await data('src/features/ecd/reading/rhymingWords.ts');
for (const round of rhymes.RHYME_ROUNDS) {
  add(`reading/rhyming/${round.id}.wav`, round.script);
  add(`reading/rhyming/prompts/${round.id}.wav`, round.prompt);
}
// Feedback exports are data; remove the audio-player import before evaluating.
let feedbackSource = fs.readFileSync('src/features/ecd/reading/readingVoice.ts', 'utf8');
feedbackSource = feedbackSource.slice(0, feedbackSource.indexOf('/** "[giggles]')).replace(/^import .*;\n/m, '');
const feedbackJs = ts.transpileModule(feedbackSource, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const feedback = await import('data:text/javascript;base64,' + Buffer.from(feedbackJs).toString('base64'));
for (const line of [...feedback.READING_PRAISE, ...feedback.READING_ENCOURAGE, feedback.READING_FINISH]) add(`phonics/feedback/${line.id}.wav`, line.script);
for (let n = 0; n <= 20; n++) add(`maths/numbers/${n}.wav`, ['Zero','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen','Twenty'][n] + '.');
for (const row of rows) {
  if (!row.script) throw new Error(`Missing script: ${row.file}`);
  fs.mkdirSync(path.dirname(row.file), { recursive: true });
}
const present = row => assets['/' + row.file.replace(/^public\//, '').replace(/\.wav$/, '')];
const intro = '# ECD complete recording checklist\n\nGenerated by `npm run ecd:audio` from the game scripts. Do not edit this generated sheet.\n\nRecord each line into the exact path listed. MP3 can replace WAV with the same filename stem. WAV takes priority when both exist. Use real PCM WAV (16-bit, mono, 44.1 or 48 kHz), not an MP3 renamed to WAV. Directions in square brackets are performed, not spoken.\n\nAfter adding recordings, restart `npm run dev` or run `npm run build` before deploying. Both refresh the audio index automatically. Missing narration uses browser speech where available; missing effects are silent. No API keys or audio conversion are required for individual clips.\n\nIndividual number files 0–20 work without timestamp mapping. Existing combined numbers recordings remain supported; run `npm run numbers:map -- public/sounds/ecd/maths/numbers.wav` after replacing that recording.\n\nExisting recording guides: [maths](ECD_MATHS_VOICE_SCRIPTS.md), [reading](ECD_READING_VOICE_SCRIPTS.md), [phonics](ECD_PHONICS_VOICE_SCRIPTS.md). Optional music and sound effects: [asset guide](ECD_MATHS_SOUND_ASSETS.md). All ECD effects accept WAV or MP3 under the same filename stem.\n\n';
fs.writeFileSync('docs/ECD_RECORDING_CHECKLIST.md', intro + rows.map(row => `### ${row.file}\n\n${present(row) ? 'Recording found: `' + present(row) + '`' : '**Needs recording**'}\n\n> ${row.script}\n`).join('\n'));
fs.writeFileSync('docs/ECD_RECORDING_CHECKLIST.json', JSON.stringify(rows, null, 2) + '\n');
fs.writeFileSync('docs/ECD_RECORDING_CHECKLIST.csv', 'file,script,status\n' + rows.map(row => [row.file, row.script, present(row) ? 'recorded' : 'missing'].map(v => '"' + v.replaceAll('"', '""') + '"').join(',')).join('\n') + '\n');
console.log(`ECD audio: ${Object.keys(assets).length} assets indexed; ${rows.length} voice scripts; ${rows.filter(row => !present(row)).length} recordings missing.`);
