import React from 'react';
import ElectricCircuitDiagram, { type CircuitKind } from './ElectricCircuitDiagram';
import { NoteSection as Section, NoteImage, Idea, Check, NoteTable as Table } from './PhysicsNotes';
const Image = ({ name, caption }: { name: string; caption: string }) => <NoteImage topic="electricity" name={name} caption={caption} />;
const CircuitPair = ({ kind, caption }: { kind: CircuitKind; caption: string }) => <div className="grid min-w-0 gap-4 xl:grid-cols-2"><Image name={kind === 'symbols' ? 'circuits' : kind} caption={caption} /><ElectricCircuitDiagram kind={kind} /></div>;
export default function Electricity() { return <div className="not-prose space-y-6">
  <Idea><p>Electricity involves electric charges. Charges can build up on an object, or flow around a complete circuit. Learn how to measure that flow, calculate the energy used, and explain how electrical devices are made safer.</p><p className="mt-3">Follow each circuit with your finger, try the calculations, and explain your answers using the ideas in the notes.</p></Idea>
  <Section title="1. Static electricity: charges that build up">
    <Image name="charging" caption="Rubbing transfers electrons between materials. The object gaining electrons becomes negative; the object losing them becomes positive." />
    <p>There are two types of charge: <strong>positive</strong> and <strong>negative</strong>. Electrons carry negative charge. Protons carry positive charge. An uncharged object has equal amounts of positive and negative charge, so its total charge is zero.</p>
    <p>When two suitable materials are rubbed together, <strong>electrons transfer</strong> from one to the other. Protons stay bound in the material. Gaining electrons makes an object negative; losing electrons makes it positive. Rubbing separates charge; it does not create charge from nothing.</p>
    <p>Rub polythene with dry cloth or hair. It usually gains electrons and becomes negative. Perspex rubbed with a suitable dry cloth usually loses electrons and becomes positive. The result depends on the pair of materials. Dry conditions help because moisture allows charge to leak away.</p>
    <Idea><strong>Like charges repel; unlike charges attract.</strong> Positive–positive and negative–negative repel. Positive–negative attract.</Idea>
    <p>A charged rod can also attract an uncharged object by shifting the charges within it slightly. The nearer side has an opposite charge, producing a stronger attraction than the repulsion from the farther side. Attraction alone therefore does not prove that both objects had opposite overall charges.</p>
    <Check question="A rod loses electrons when rubbed. What charge does it gain, and why?"><p>It becomes positive. It has lost negative charge, leaving more positive charge than negative charge. It has not gained protons.</p></Check>
  </Section>
  <Section title="2. Current, conductors and insulators">
    <p><strong>Electric current</strong> is the rate of flow of charge. Its SI unit is the <strong>ampere (A)</strong>. In a metal wire, moving electrons carry charge. Conventional current is shown from positive to negative through the external circuit; the electrons move in the opposite direction.</p>
    <p>A <strong>conductor</strong> allows charge to move through it easily. Copper and other metals are examples. An <strong>insulator</strong> does not allow charge to flow easily; plastic, glass and dry wood are examples. A cable uses conducting metal inside and insulating plastic outside.</p>
    <p>To compare conductivity, build a low-voltage circuit with a cell, switch and bulb, leaving a gap for a sample. Put each material across the same gap. A lit bulb shows that the sample completes a conducting path. Keep the cell and bulb unchanged. A very small current may not light the bulb, so an ammeter can help detect weaker conduction.</p>
    <p>Current needs a <strong>complete path</strong>. Opening a switch breaks that path. The cell supplies energy to the charges; it does not supply a flow that gets used up at the bulb.</p>
  </Section>
  <Section title="3. Drawing a d.c circuit">
    <CircuitPair kind="symbols" caption="Use standard symbols joined by straight lines. A simple d.c circuit has a supply and a complete path through its components." />
    <p><strong>Direct current (d.c.)</strong> flows in one direction. A cell provides an electrical supply; a battery is a group of cells. A bulb transfers electrical energy to light and heat. A switch opens or closes the path. A resistor limits current; a variable resistor lets you change the resistance.</p>
    <p>In a cell symbol, the <strong>long line is positive</strong> and the short line is negative. Draw wires as straight lines. Label components clearly. Put a dot where wires join; crossing lines without a junction dot should not be mistaken for a connection.</p>
    <p>Draw a cell, switch and bulb in one loop. Check that closing the switch gives a continuous route from one cell terminal, through the bulb, to the other terminal. Do not draw a wire straight across the bulb: that would bypass it. Practise interpreting a diagram by tracing every branch before building it.</p>
  </Section>
  <Section title="4. Measuring current and voltage">
    <CircuitPair kind="meters" caption="An ammeter is in series with the resistor. A voltmeter connects in parallel across the resistor’s two terminals." />
    <p><strong>Voltage</strong>, or potential difference, describes the energy transferred per unit charge between two points. Its SI unit is the <strong>volt (V)</strong>. Current tells you how quickly charge flows; voltage tells you the energy change for each unit of charge.</p>
    <p>Connect an <strong>ammeter in series</strong> so the current being measured passes through it. Connect a <strong>voltmeter in parallel</strong> across the component so it compares the two ends. For d.c meters, connect the positive terminal towards the supply’s positive side and choose a suitable range.</p>
    <p>An ammeter has very low resistance. Connecting it directly across a supply can cause a large current. A voltmeter has high resistance, so it takes only a small current when correctly connected.</p>
    <Idea><p><strong>Power = voltage × current: P = VI.</strong></p><p className="mt-2">A lamp with 6 V across it and a current of 0.5 A has power P = 6 × 0.5 = <strong>3 W</strong>.</p></Idea>
    <Check question="Where should you connect meters to find the power of a bulb?"><p>Put the ammeter in series with the bulb and the voltmeter across the bulb. Multiply the bulb’s current by the voltage across it: P = VI.</p></Check>
  </Section>
  <Section title="5. Using an electroscope">
    <Image name="electroscope" caption="The metal cap, stem and leaf conduct charge. The leaf separates from the stem when they have like charges." />
    <p>An <strong>electroscope</strong> detects electric charge. A metal cap connects to a metal stem and a thin conducting leaf. An insulating support prevents charge from escaping easily. If the leaf and stem have the same kind of charge, they repel, and the leaf rises away from the stem.</p>
    <p>Discharge it by briefly touching the cap, then remove your hand. Bring a negatively charged rod near the cap without touching it. Electrons in the electroscope move away from the rod towards the stem and leaf. The cap is left relatively positive, while the stem and leaf become negative and repel. This is <strong>induction</strong>: the electroscope as a whole remains neutral in this simple test. Remove the rod and the leaf falls back.</p>
    <p>Touch the cap with a suitable charged rod. Charge can transfer by <strong>contact</strong>. After removing the rod, the leaf can remain raised because the electroscope has gained a net charge. With an insulating rod, the amount transferred depends on contact and the materials used.</p>
    <p>To compare charge signs, first charge the electroscope with a known sign. Bring an unknown charged object near its cap without touching. With a modest approach, the same sign increases the leaf’s separation; the opposite sign initially reduces it. A neutral electroscope alone cannot identify the sign, and bringing a strong opposite charge too close can make the leaf rise again.</p>
    <Check question="Why does an electroscope leaf rise?"><p>The leaf and stem carry like charges. They repel each other, so the light leaf moves away from the stem.</p></Check>
  </Section>
  <Section title="6. Lightning and a lightning conductor">
    <p>During a storm, charges separate in clouds. This can produce a large voltage between cloud and ground. If the electric field becomes strong enough to make air conduct, a rapid discharge passes through it: <strong>lightning</strong>. Lightning can also pass between clouds.</p>
    <p>A lightning conductor has a metal air terminal high on the building, a continuous conducting path down the building, and a connection to earth. Its purpose is to intercept a strike and carry the large current to ground along a planned path, reducing damage. Height, good conduction and effective earthing work together; an unconnected metal rod is not a complete protection system.</p>
    <p>Lightning can cause electrocution, severe heating, burns and fires. Shelter in a substantial building or a closed, hard-topped vehicle. Avoid isolated trees, open ground and water. Indoors, stay away from plumbing and corded electrical equipment during a storm. Wait at least 30 minutes after the last thunder before returning outside.</p>
    <p>Red clothes do not cause lightning. Ordinary rubber shoes do not protect a person from a strike. Discuss these myths using charge, voltage and conduction rather than superstition. Examine a lightning-conductor model; a real installation belongs to trained installers. <a className="text-sky-700 underline" href="https://www.weather.gov/safety/lightning-safety" target="_blank" rel="noreferrer">Lightning safety guidance</a>.</p>
  </Section>
  <Section title="7. Ohm’s law and resistance">
    <p><strong>Resistance</strong> describes how much a component opposes current. Its unit is the <strong>ohm (Ω)</strong>. Ohm’s law says current is directly proportional to voltage for a conductor <strong>at constant temperature and other physical conditions</strong>.</p>
    <Idea><p><strong>V = IR; I = V/R; R = V/I.</strong></p><p className="mt-2">Across a 4 Ω resistor, 12 V gives I = 12 ÷ 4 = <strong>3 A</strong>. A current of 0.2 A through 30 Ω requires V = 0.2 × 30 = <strong>6 V</strong>. If V = 8 V and I = 0.4 A, R = 8 ÷ 0.4 = <strong>20 Ω</strong>.</p></Idea>
    <p>Use the meter circuit above to measure resistance. Start with a small current, record V across the resistor and I through it, then vary the supply or variable resistor to obtain several pairs. Calculate V/I for each pair. A constant ratio supports Ohm’s law; a V-against-I graph is a straight line through the origin. Keep the resistor’s temperature as steady as possible.</p>
    <p>Ohm’s law does not describe every component under every condition. A filament lamp heats up, so its resistance changes. A diode has different behaviour in opposite directions. You can still calculate V/I at a particular operating point, but the ratio need not remain constant.</p>
    <p>For wires of the <strong>same material at the same temperature</strong>, a longer wire has greater resistance; a thicker wire, with a larger cross-sectional area, has lower resistance. Doubling length doubles resistance. Doubling area halves resistance. Area is not the same as diameter: doubling a circular wire’s diameter makes its area four times as large.</p>
    <Check question="Why must the wire’s temperature stay constant when testing Ohm’s law?"><p>A temperature change can change the resistance. Then current may no longer be directly proportional to voltage, so changing temperature would interfere with the test.</p></Check>
  </Section>
  <Section title="8. Resistors in series and parallel">
    <CircuitPair kind="resistors" caption="In series, resistances add. In parallel, each resistor connects between the same two junctions." />
    <p>In <strong>series</strong>, components are one after another in a single path. The same current passes through them, while the supply voltage is shared.</p>
    <Idea><p>R<sub>total</sub> = R₁ + R₂ + R₃.</p><p className="mt-2">2 Ω + 4 Ω = <strong>6 Ω</strong>. With a 12 V supply, I = 12 ÷ 6 = <strong>2 A</strong>. The voltage drops are 2 × 2 = 4 V and 2 × 4 = 8 V, adding to 12 V.</p></Idea>
    <p>In <strong>parallel</strong>, each branch connects across the same two points. Each branch has the same voltage. The total current is the sum of the branch currents.</p>
    <Idea><p>1/R<sub>total</sub> = 1/R₁ + 1/R₂ + 1/R₃.</p><p className="mt-2">For 6 Ω and 6 Ω in parallel, 1/R<sub>total</sub> = 1/6 + 1/6 = 1/3, so R<sub>total</sub> = <strong>3 Ω</strong>. Remember to take the reciprocal at the end.</p></Idea>
    <p>For two resistors you can also use R<sub>total</sub> = R₁R₂/(R₁ + R₂). For 3 Ω and 6 Ω, this gives 18/9 = <strong>2 Ω</strong>. A parallel total is less than the smallest branch resistance because there are additional paths for current.</p>
    <p>Build low-voltage circuits from a cell, switch, resistors, variable resistor, bulb and meters. Use the variable resistor to control current. Include an appropriate fuse where required. Draw the circuit before building it, and check whether each component belongs in the main path or a branch.</p>
    <Check question="Two 10 Ω resistors are connected first in series, then in parallel. Find each total."><p>Series: 10 + 10 = <strong>20 Ω</strong>. Parallel: 1/R = 1/10 + 1/10 = 1/5, so <strong>R = 5 Ω</strong>.</p></Check>
  </Section>
  <Section title="9. Electrical power and energy">
    <p><strong>Power</strong> is the rate of energy transfer. A watt is one joule per second. <strong>Energy</strong> is the amount transferred over time. An appliance with a large power rating transfers energy quickly, but its total energy use also depends on how long it runs.</p>
    <Idea><p><strong>P = VI; E = Pt = VIt.</strong></p><p className="mt-2">Use volts, amperes and seconds to get energy in joules. A 12 V device using 2 A for 30 s transfers E = 12 × 2 × 30 = <strong>720 J</strong>.</p></Idea>
    <p>For electricity bills, use <strong>kilowatt-hours (kWh)</strong>. This is an energy unit: 1 kWh is the energy used by a 1 kW appliance in one hour. It equals 3 600 000 J. It is not “kilowatts per hour”.</p>
    <Idea><p>Energy (kWh) = power (kW) × time (h).</p><p className="mt-2">A 2000 W heater is 2 kW. In 1.5 hours it uses 2 × 1.5 = <strong>3 kWh</strong>. A 60 W lamp running for 5 hours uses 0.060 × 5 = <strong>0.30 kWh</strong>.</p></Idea>
    <Check question="Which uses more energy: a 1 kW appliance for 2 hours or a 2 kW appliance for half an hour?"><p>The first uses 1 × 2 = <strong>2 kWh</strong>. The second uses 2 × 0.5 = <strong>1 kWh</strong>. Comparing power alone is not enough; include the time.</p></Check>
  </Section>
  <Section title="10. Hazards, fuses and plugs">
    <div className="grid min-w-0 gap-4 xl:grid-cols-2"><Image name="plug" caption="Inside a fused three-pin plug: live is brown, neutral blue, earth green/yellow. The fuse is in the live connection." /><Image name="plug-exam" caption="Exam-style image: earth at the top, neutral on the left, and the fuse in the live connection." /></div>
    <Table headings={['Hazard', 'Why it is dangerous / how to reduce it']} rows={[
      ['Damaged insulation', 'Exposed live conductors can cause a shock. Stop using damaged cables and have them replaced.'], ['Overloaded circuits', 'Too much current heats cables and can start a fire. Do not overload sockets or extension leads.'], ['Damp conditions', 'Moisture can make a conducting path through a person. Keep hands and equipment dry.'], ['Unearthed metal case', 'A fault may make the case live. Suitable appliances need a sound earth connection.'],
    ]} />
    <p>The <strong>live</strong> wire supplies the alternating voltage. The <strong>neutral</strong> completes the normal circuit. The <strong>earth</strong> connects an exposed metal case to ground; it normally carries no current. If live touches an earthed case, a large fault current can make the protective device disconnect the supply.</p>
    <p>A <strong>fuse</strong> melts when excessive current heats it, breaking the circuit. Choose a suitable rated fuse; never replace it with ordinary wire. Put the fuse and switch in the live wire so they disconnect the appliance from live. A fuse mainly protects against excessive current; it is not a guarantee against every electric shock.</p>
    <p>Modern flexible-cable colours are <strong>brown = live; blue = neutral; green/yellow = earth</strong>. Older red/live, black/neutral and green/earth colours may appear in older examples. Use terminal markings, not guesses based on an unfamiliar cable. The cable grip holds the outer sheath, not just the individual wires.</p>
    <p>A <strong>double-insulated</strong> appliance has an extra protective layer between live parts and the outside, shown by a square inside a square. It does not need a protective earth connection and can use a two-conductor connection or a suitable two-pin plug. A two-pin plug alone does not prove an appliance is double insulated.</p>
    <p>Practise identifying and wiring terminals on a disconnected classroom plug under supervision. Demonstrate a fuse or switch using a low-voltage model. Insulated cables and dry hands matter; ordinary rubber footwear is not a substitute for proper electrical protection. <a className="text-sky-700 underline" href="https://www.electricalsafetyfirst.org.uk/safety-advice/home-and-people/house-maintenance/plugs-and-fuses/" target="_blank" rel="noreferrer">Plug wiring guidance</a>.</p>
    <Check question="Why is the fuse connected in live rather than neutral?"><p>When it melts, it breaks the live supply to the appliance. A fuse only in neutral could interrupt current while leaving internal parts connected to live.</p></Check>
  </Section>
  <Section title="11. Electricity at home and solar photovoltaic systems">
    <Image name="solar" caption="Photovoltaic panels produce electricity from light. A controller can charge a battery, and an inverter can supply a.c appliances." />
    <p>Homes use electricity for lighting, heating and powering devices such as refrigerators, televisions and computers. An electricity meter records energy used.</p>
    <Idea><p>Units used = later meter reading − earlier reading.<br />Energy charge = units used × price per kWh.</p><p className="mt-2">If readings are 1240 and 1275 kWh, usage is <strong>35 kWh</strong>. At an example tariff of $0.20 per kWh, the energy charge is 35 × 0.20 = <strong>$7.00</strong>. This is a practice tariff; fixed charges or tariff bands may also appear on a real bill.</p></Idea>
    <p>Save energy by switching off unused appliances, choosing energy-saving bulbs, and comparing energy use for the same useful job. A lower power rating is not automatically better: an appliance that takes much longer can use more total energy. Insulation and efficient heating also reduce energy use.</p>
    <p><strong>Solar photovoltaic (PV) cells</strong> convert light directly into electrical energy. Panels supply d.c. A charge controller manages battery charging where a battery is used; a battery stores energy for later. An inverter changes d.c to a.c for suitable household appliances. Solar panels do not produce electricity from sunlight at night; stored energy or another source is then needed.</p>
    <p>Solar panels and biogas can reduce dependence on purchased electricity. Biogas can replace electricity for some heating or cooking tasks. Alternative energy sources change where energy comes from; they do not make the appliance’s energy need disappear. A solar water heater heats water and is different from a photovoltaic panel.</p>
    <Check question="A 100 W lamp runs for 10 hours. At $0.20 per kWh, what is its energy cost?"><p>100 W = 0.1 kW. Energy = 0.1 × 10 = <strong>1 kWh</strong>. Cost = 1 × $0.20 = <strong>$0.20</strong>.</p></Check>
  </Section>
</div>; }
