import catalogue from './questionPapers.json';

/**
 * The question papers that ship with the app.
 *
 * This file supplies academic metadata for the entries in
 * `public/qpandbooks.json`. The archive resolves each catalogue path to its
 * Drive URL before opening it. ZIMSEC and Cambridge sit in one list — a learner
 * looking for A-Level Physics wants both — and the board rides along on each
 * paper so a card can say which exam it belongs to.
 *
 * Generated by `scripts/buildQuestionPaperCatalogue.mjs`; re-run that after
 * adding files rather than editing this by hand.
 */

export interface CataloguePaper {
  id: string;
  board: 'ZIMSEC' | 'Cambridge';
  /** The archive level this is filed under — "O' Level", "A' Level". */
  course: string;
  subject: string;
  /** The sitting: "November 2024", "Specimen", "Green Book". */
  year: string;
  /** "Paper 2", "Paper 4 (Variant 3)", "Syllabus". */
  type: string;
  name: string;
  url: string;
  size: string;
}

export const QUESTION_PAPERS = catalogue.papers as CataloguePaper[];

/** The papers filed under one level, in catalogue order. */
export const papersForCourse = (course: string) =>
  QUESTION_PAPERS.filter((paper) => paper.course === course);
