import catalogue from './questionPapers.json';
import { IMPORTED_RESOURCES } from './importedResources';

/**
 * The question papers that ship with the app.
 *
 * This file supplies academic metadata for the entries in
 * `public/qpandbooks.json`. The archive resolves each catalogue path to its
 * Drive URL before opening it. ZIMSEC and Cambridge sit in one list — a learner
 * looking for A-Level Physics wants both — and the board rides along on each
 * paper so a card can say which exam it belongs to.
 *
 * Generated by `scripts/buildQuestionPaperCatalogue.mjs`; re-run that after
 * adding files rather than editing this by hand.
 */

export interface CataloguePaper {
  id: string;
  board: string;
  /** The archive level this is filed under — "O' Level", "A' Level". */
  course: string;
  subject: string;
  /** The sitting: "November 2024", "Specimen", "Green Book". */
  year: string;
  /** "Paper 2", "Paper 4 (Variant 3)", "Syllabus". */
  type: string;
  name: string;
  url: string;
  size: string;
  coverUrl?: string;
}

const importedPapers: CataloguePaper[] = IMPORTED_RESOURCES.filter((item) => item.type === 'past-papers').map((item) => ({
    id: item.id,
    board: item.board,
    course: item.course,
    subject: item.subject,
    year: item.year,
    type: item.paperType,
    name: item.title,
    url: item.url,
    size: item.size,
    coverUrl: item.coverUrl,
  }));

const paperKey = (paper: CataloguePaper) =>
  [paper.board, paper.course, paper.subject, paper.year, paper.type].join('|');
const importedKeys = new Set(importedPapers.map(paperKey));

// A verified replacement scan must open its current Drive file, even when an
// older bundled scan has the same academic detail URL.
export const QUESTION_PAPERS: CataloguePaper[] = [
  ...catalogue.papers.filter((paper) => !importedKeys.has(paperKey(paper))),
  ...importedPapers,
];

/** The papers filed under one level, in catalogue order. */
export const papersForCourse = (course: string) =>
  QUESTION_PAPERS.filter((paper) => paper.course === course);
